### ISSUE TITLE
Re-usable complex fields

### ISSUE THREAD

**Issue by berndca** [gcanti/tcomb-form#103]
I have more than 100 forms built from a set of more or less complex input field types in my app. One of the most common field type is a struct combining an integer value with an optional dict of attributes.

NumExpression = t.struct({
  text: t.Num
  attributes: t.maybe(t.dict(t.Str, t.union([t.Str, t.Num])))
}, 'NumExpression')

It appears maybe dict's are not supported. Do I have to create my own factory for this or is there another way to create a re-usable complex field?

Thanks, Bernd

**Comment by gcanti** [comment]
Hi,
interesting problem. 

> Do I have to create my own factory for this

Yes, for 3 reasons:

- `union`s are not supported `t.union([t.Str, t.Num])`
- `dict`s are not supported `t.dict(t.Str, t.union([t.Str, t.Num]))`
- `maybe`s of complex types are not supported

There's nothing inherently difficult, the biggest problem is defining the UI of such types, in particular
the UI for a `union` and the UI for a `maybe(dict...)`

(One day I hope to add ufficial support for such types, this issue could be the seed)

---

**Musings**

To lower the effort (and if it's acceptable from a UX point of view) 
theorically `dict`s could be replaced by `list`s ...

```
t.dict(t.Str, t.union([t.Str, t.Num])) ~> t.list(t.struct({
  key: t.Str,
  value: t.union([t.Str, t.Num]))
}))
```

... plus an additional transformation `dict <-> list`.

`maybe` could be replaced by the rule:

```
[] <-> null // arrays with 0 elements are equivalent to null
```

The `union` problem still stands: how to represent a union in a UI? 

- tabs containing the inputs (a tab for each element of the union)?
- radios with inputs aside (a radio for each element of the union)?
- other ideas?

In your *specific case* there could be a workaround handling the `union` in the tranformation:

```
input value <-> Num if is parsable, Str otherwise
```

but it's kinda hacky if it works.

If you are interested, I could put up an example in the current version on master (v0.5-beta)

Giulio

**Comment by gcanti** [comment]
Here an example using the current version (v0.4.8) and a transformation outside tcomb-form:

```js
var React = require('react');
var t = require('tcomb-form');

var Form = t.form.Form;

var NumExpression = t.struct({
  text: t.Num,
  attributes: t.maybe(t.dict(t.Str, t.union([t.Str, t.Num])))
}, 'NumExpression')

// a version of NumExpression where dict is converted to a list
var TcombNumExpression = t.struct({
  text: t.Num,
  attributes: t.list(t.struct({
    key: t.Str,
    value: t.Str
  }))
}, 'TcombNumExpression');

// from TcombNumExpression to NumExpression
TcombNumExpression.prototype.toNumExpression = function() {
  var value = {
    text: this.text
  };
  if (this.attributes.length) {
    var attributes = {};
    this.attributes.forEach(function (pair) {
      attributes[pair.key] = pair.value; // <- here you could convert the string pair.value to a number if it is possible
    });
    value.attributes = attributes;
  }
  return new NumExpression(value);
};

// a larger model containing NumExpression
var Model = t.struct({
  field1: t.Str,
  field2: t.Str,
  numexpression: NumExpression
}, 'Model');

// corresponding tcomb model
var TcombModel = t.struct({
  field1: t.Str,
  field2: t.Str,
  numexpression: TcombNumExpression
}, 'TcombModel');

// from TcombModel to Model
TcombModel.prototype.toModel = function() {
  var value = {
    field1: this.field1,
    field2: this.field2,
    numexpression: this.numexpression.toNumExpression()
  };
  return new Model(value);
};

// an initial value for tests
var value = {
  field1: 'field1 value',
  field2: 'field2 value',
  numexpression: {
    text: 1,
    attributes: [
      {key: 'a', value: 'a value'}
    ]
  }
};

var App = React.createClass({

  save: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value.toModel()); // <-- instance of Model
    }
  },

  render: function() {
    return (
      <div>
        <Form ref="form"
          type={TcombModel}
          value={value}
        />
        <button className="btn btn-primary" onClick={this.save}>Save</button>
      </div>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Comment by berndca** [comment]
Giulio,

thanks for sharing your insights and providing the detailed example. I agree, that introducing a dedicated UI model creates much more flexibility and a lot of issues can be handled either inside this model or in the method converting to the reference schema model. We'll probably need another conversion method to convert existing data to UI model format for editing. Which should not be a problem.

With this approach I would be able to avoid creating a lot of factory modules and could use template(s) instead. Which brings me back to the main issue of re-usable fields. I read through the templates section of the guide and I'm confused about how to speficy templates. I would like to use a custom template to render the form. So I specified options.templates: { struct: this.myFormTemplate }. Now some of the fields are struct themself and I need to use a different template for each field. But I don't seem to be able to do this since all structs are rendered with myFormTemplate. Is there a way to specify the different templates for the form and  it's fields, especially fields of type struct? Would you recommend to implement re-usable fields as custom components?

Thanks, Bernd

**Comment by gcanti** [comment]
Options can be set in a recursive manner, maybe this issue https://github.com/gcanti/tcomb-form/issues/69
and the following example can clarify (this is made by hand but obviously if you have a schema you can produce the `options` automatically):

```js
var React = require('react');
var t = require('tcomb-form');

var Form = t.form.Form;

// nested structs
var Type = t.struct({
  a: t.struct({
    c: t.Str,
    d: t.Str
  }),
  b: t.struct({
    e: t.Str,
    f: t.Str
  }),
  g: t.struct({
    h: t.Str,
    i: t.Str
  })
});

function topTemplate(locals) {
  return (
    <div>
    <p>topTemplate</p>
    {Object.keys(locals.inputs).map(function (k) {
      return locals.inputs[k];
    })}
    </div>
  );
}

function aTemplate(locals) {
  return (
    <div>
    <p>aTemplate</p>
    {Object.keys(locals.inputs).map(function (k) {
      return locals.inputs[k];
    })}
    </div>
  );
}

function bTemplate(locals) {
  return (
    <div>
    <p>bTemplate</p>
    {Object.keys(locals.inputs).map(function (k) {
      return locals.inputs[k];
    })}
    </div>
  );
}

function cTemplate(locals) {
  return <div>cTemplate</div>;
}

var options = { // <-- this is a struct, use `templates`
  templates: {
    struct: topTemplate // this will be used as default from now on
  },
  fields: {
    a: { // <-- this is a struct, use `templates` to override the new default topTemplate
      templates: {
        struct: aTemplate
      },
      fields: {
        c: { // <- this is a field, use `template` to override the default template
          template: cTemplate
        }
      }
    },
    b: { // <-- this is a struct, use `templates` to override the new default topTemplate
      templates: {
        struct: bTemplate
      }
    },
    g: {
      templates: { // <-- restore the true default template for the g struct!
        struct: t.form.config.templates.struct
      }
    }
  }
};

var App = React.createClass({

  save: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render: function() {
    return (
      <div>
        <Form ref="form"
          type={Type}
          options={options}
        />
        <button className="btn btn-primary" onClick={this.save}>Save</button>
      </div>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Comment by gcanti** [comment]
> Would you recommend to implement re-usable fields as custom components?

If your goals are custom layouts, I'd say no. Stick with the default components provided by tcomb-form and play with the `templates` option.
v0.5 will be more friendly in order to write custom components, v0.4 is quite complex so I think it doesn't worth.

Custom components are mainly useful when you want to handle a new type (like t.Dat or dicts, tuples, ecc...)

Keep in mind that tcomb's types are fully analyzable through runtime introspection:
Every type owns a `meta` property describing the type itself (http://gcanti.github.io/tcomb/guide/index.html#meta), so you can do great things with a little bit of automation.


If you have questions, problems or examples to share, feel free to contact me. I'm always interested to play with types, options and runtime introspection (moreover your use case could improve the v0.5 which I'm finalizing these days).

**Comment by berndca** [comment]
Thanks, I incorrectly assumed the struct api (template**s**) would be the same as the Textbox api (template). Thanks for the clarification.

The **biggest challenge** I see mapping my target schema to tcomb-forms is the **lack of support for maybe of struct and list.** The UI models do help to address this, but built-in support would be very helpful.

Thanks, Bernd

**Comment by Coobaha** [comment]
@gcanti is the use of struct, with fields custom factories option, passed to list is supported?

code example:

```es6
let Type = t.struct({
      persons   : t.list(PersonStruct)
});

let PersonStructOptions = {
  name         : {
    factory : NameInput
  },
  passport     : {
    factory  : PassportInput,
    patterns : somePattern
  },
  personDate   : {
    factory : ComboDate,
    minYear : 1900,
    maxYear : new Date().getFullYear()
  }
}

let options = {
      fields : {
        persons  : PersonStructOptions
      }
};
```

I also tried with items key name

**Comment by gcanti** [comment]
Yes, you can nest types and options at arbitrary levels.

In order to configure list items you can use the `item` option: https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#items-configuration.

In your case it would be:

```js
let options = {
  fields: {
    persons: {
      item: {
        fields: PersonStructOptions
      }
    }
  }
};
```
