### ISSUE TITLE
Any possible way to remove has-error class when form submit?

### ISSUE THREAD

**Issue by sunglee** [gcanti/tcomb-form#104]
Thank you for the awesome library!

I am trying to add shake css animation to input field. In css
```css
.has-error input {
/* css animation codes */
}
```
In jsx, when submit event occurs, I want to remove .has-error class(es) in all form fields and re-evaluate them to show animation again if error occurs.
All I can think of is use getElementsByClassName and loop to remove .has-error class. Is there a function inside tcomb-form to reset error?

**Comment by gcanti** [comment]
Hi, thanks.

> Is there a function inside tcomb-form to reset error?

Officially, no.

Unofficially, as a workaround, you could get the inner components through `refs` and set the error state by hand, e.g.

```js
var MyType = t.struct({
  name: t.Str,
  surname: t.Str
});

...

<Form ref="form" type={MyType} />

...

this.refs.form.refs.input.refs.name.setState({hasError: true});
this.refs.form.refs.input.refs.surname.setState({hasError: true});


```
