### ISSUE TITLE
Dict validation 0.5-beta: duplicate domain values

### ISSUE THREAD

**Issue by berndca** [gcanti/tcomb-form#105]
I was playing new experimental Dict feature of the 0.5-beta and I was wondering if you could add a check for duplicate keys (domain values) to the Dict validation. Currently it just returns the last key/ value pair quietly. I have some cases with more than 10 key, value pairs and suspect that the user might accidently use the same key more than once. It would be nice if this could be caught.

Thanks, Bernd

**Comment by gcanti** [comment]
:+1:

**Comment by gcanti** [comment]
Since I don't know when I'll be able to add a reliable `Dict` component, I wrote a little example using the current version, a `List` component and the `error` option:

```js
// returns info on duplicated keys if found, null otherwise
function duplicatedKeys(value) {
  var keys = {};
  for (var i = 0, len = value.length ; i < len ; i++ ) {
    if (keys.hasOwnProperty(value[i].domain)) {
      return [value[i].domain, keys[value[i].domain], i];
    }
    keys[value[i].domain] = i;
  }
}

// original type: t.dict(t.Str, t.Str)
var Type = t.subtype(t.list(t.struct({ // <-- a subtype in order to enforce uniqueness
  domain: t.Str,
  codomain: t.Str
})), function (x) {
  return !duplicatedKeys(x);
});

var options = {
  error: function (value) {
    var keys = duplicatedKeys(value);
    if (keys) {
      return 'Duplicated key "' + keys[0] + '" in position #' + (keys[1] + 1) + ' and #' + (keys[2] + 1);
    }
  },
  item: {
    fields: {
      domain: {
        label: 'ISO Code'
      },
      codomain: {
        label: 'Description'
      }
    }
  }
};

var value = [
  {domain: 'IT', codomain: 'Italy'},
  {domain: 'US', codomain: 'United States'},
  {domain: 'IT', codomain: 'Fance'} // <-- duplicated key for tests
];

var App = React.createClass({

  save() {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render() {

    return (
      <div>
        <Form ref="form"
          type={Type}
          options={options}
          value={value}
        />
        <button className="btn btn-primary" onClick={this.save}>Save</button>
      </div>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Comment by berndca** [comment]
Thanks! I went ahead and tried to create templates for both the list and the struct. The struct inputs are arranged in a table row and the list template is comprised of the outer table element plus thead, wrapping all rows with tbody. Arranging all the inputs this way worked very well. However I hit a wall trying to bind the onClick methods of the 3 buttons (Remove, Up, Down) in the context of  table row representing the struct. I would need access to the list object, but this context is not available in the locals passed to the struct template. I thought about creating a list template which renders the entire form including the struct inputs, however it seems rather complex. Am I missing something? Is there an easier way to do this?

Thanks, Bernd

**Comment by gcanti** [comment]
Yeah, I hit that wall as well. This is my attempt yesterday:

```js
function listTemplate(locals) {
  return (
    <div>
      <table className="table">
        <thead>
          <th>Domain</th>
          <th>Codomain</th>
          <th>Buttons</th>
        </thead>
        <tbody>
          {
            locals.items.map(function (item) {
              return (
                <tr key={item.key}>
                  {item.input} {/* HERE'S THE PROBLEM! see structTemplate */}
                  <td>
                    <div className="btn-group">
                      {
                        item.buttons.map(function (button, i) {
                          return <button key={i} className="btn btn-default" onClick={button.click}>{button.label}</button>;
                        })
                      }
                    </div>
                  </td>
                </tr>
              );
            })
          }
        </tbody>
      </table>
      <button className="btn btn-default" onClick={locals.add.click}>{locals.add.label}</button>
    </div>
  );
}

function structTemplate(locals) {
  // React doesn't allow adjacent JSX elements

  /*
  return (
    <td>{locals.inputs.domain}</td>
    <td>{locals.inputs.codomain}</td>
  );
  */

  // hack...

  return (
    <div>
      <td>{locals.inputs.domain}</td>
      <td>{locals.inputs.codomain}</td>
    </div>
  );
}

var Type = t.list(t.struct({
  domain: t.Str,
  codomain: t.Str
}));

var options = {
  template: listTemplate,
  item: {
    auto: 'none',
    template: structTemplate
  }
};
```

**Comment by berndca** [comment]
Thanks for the response! This problem appears to be related to complex nested types.

This would be much easier if there would be way to access the struct inputs directly from the list effectively skipping on level of hierarchy. So one could wrap the Textboxes for codomain and domain in a td within the list template. Is there perhaps a method one could call on struct to get these inputs?

Thanks, Bernd

**Comment by gcanti** [comment]
Unfortunately there's no way to access the struct inputs directly from the list.
In `locals` you get `ReactElement`s, so everything is already packed by React.

What I regret is that this is simply a layout problem but due to the `table` markup and the limitation of the render method, it ends up to be more difficult than it should be

**Comment by berndca** [comment]
Thanks. Since wrapping td's in a div is not legal HTML I can not use a table. Fortunately we are already using bootstrap, so I changed the form from table to rows and columns using boostrap's grid system. It's not perfect, but I think it's workable.

Thanks, Bernd
