### ISSUE TITLE
Dict custom templates 0.5-beta

### ISSUE THREAD

**Issue by berndca** [gcanti/tcomb-form#106]
I'm trying to pass a custom template function to the dict, however ot does not seem to use it.

The goal is to render the dict as table with three columns, the first two for domain and codomain and the last one for the control buttons (up, down remove). The column headers should be user defined.

I'm using the render function from https://github.com/gcanti/gcanti.github.io/blob/master/tcomb-form/guide/src.js and tcomb-form 0.5-beta. My template function is called dictTable.

var Attributes = t.dict(t.Str, t.Str);
var options = {
    templates: {
        dict: dictTable
    }
};
var value = {a: '42'};
render('1', Attributes, options, value);

Please advise.
Thanks, Bernd

**Comment by gcanti** [comment]
Given the current implementation (it uses a `List` component internally), it's hard: 
domain and codomain are tight together in a struct so they are rendered as a single input 
(no way to easily split domain and codomain inputs).

Having a solution for this issue and #105 means to develop a truly specialized `Dict` component.
These days I'm back-porting some features from v0.5 to v0.4.9, I'll try to add such a `Dict` component
to v0.4.9 (v0.5 goes in standby).

**Comment by berndca** [comment]
Thanks for your support!

Bernd
