### ISSUE TITLE
Usage question regarding React and onChange.

### ISSUE THREAD

**Issue by marr** [gcanti/tcomb-form#110]
I am having difficulty with tcomb-form and react, surely its on my end but I'm not sure why onChange wouldn't fire in the case of this component:

```
'use strict';
import React from 'react';

var
    t = require('tcomb-form'),
    Form = t.form.Form,
    CreditCard = t.struct({
        number: t.Str,
        security: t.Str
    });

export default class CreditCardForm extends React.Component {
    render() {
        return <div>
            <Form type={CreditCard} onChange={this.onChange}/>
        </div>;
    }
}

CreditCardForm.prototype.onChange = function(rawValue) {
    console.log(rawValue); // not firing
};
```
Is my ES6 syntax wrong? My OO concept here totally mistaken? I've read comments in the React repo saying not to use class syntax with React, so my thinking is I've hit a snag somewhere along that path.

https://github.com/marr/cards

This is my starter repo to play with tcomb-form, hopefully I can get it working as the docs explain soon.

**Comment by gcanti** [comment]
Hi,
Just made a quick test and it works for me, I can see the `rawValue` in the console.
Regarding your repo: the `dependencies` property in `package.json` is missing, it's difficult to reproduce your exact setup

**Comment by marr** [comment]
Thanks Giulio,
I just updated the package dependencies. Appreciate the heads up about
that.

After cloning on another machine, and running the dev server `npm run dev`
I do see things working.
Blaming this on bad browser cache on other machine maybe ;)

Dave

**Comment by gcanti** [comment]
:+1:
