### ISSUE TITLE
React gets installed twice, leading to weird issues

### ISSUE THREAD

**Issue by orestis** [gcanti/tcomb-form#111]
Hello, I'm evaluating tcomb-form for an internal tool. I'm very new to the whole npm world, so this might be a user error, perhaps an easy to fall down to:

I start from scratch doing:

    npm install tcomb-form

I end up with:

node_modules:
```
react
tcomb
tcomb-form
tcomb-validation
```

but tcomb-form/node_modules is:

```
 debug
 react
 uvdom
 uvdom-bootstrap
```

Meanwhile, I get these warnings from nom:

```
npm WARN peerDependencies The peer dependency react@>=0.12.0 included from tcomb-form will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency tcomb-validation@^1.0.3 included from tcomb-form will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@>=0.12.0 included from uvdom will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency tcomb@^1.0.0 included from tcomb-validation will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

I got some clue about this from http://stackoverflow.com/questions/28519287/what-does-only-a-reactowner-can-have-refs-mean and #107 

The solution is to first install react and then install tcomb-form, then react doesn't get installed again.

**Comment by gcanti** [comment]
Hi, thanks for the report.

> The solution is to first install react and then install tcomb-form, then react doesn't get installed again.

It seems the new way to handle `peerDependecies`.

https://github.com/npm/npm/issues/6565#issuecomment-76482462
