### ISSUE TITLE
Remove class "has-error" from empty optional field

### ISSUE THREAD

**Issue by berndca** [gcanti/tcomb-form#113]
I have an optional Num field in a struct. When an incorrect value for this Num field is found during validation the "has-error" class is added to the enclosing form-group as it should be. However when I delete the incorrect value and re-validate the form with the now empty optional field the "has-error" class does not get removed. I replicated this issue on the tcomb-form playground.

Please advise.
Thanks, Bernd

**Comment by gcanti** [comment]
Thanks, working on this
