### ISSUE TITLE
Numbers don't validate as strings

### ISSUE THREAD

**Issue by orestis** [gcanti/tcomb-form#114]
Possibly related to #60 

I have a very simple form:

```
var Overview = t.struct({
    content: t.maybe(t.Str)
});
```

I type in the input field the value 123.

tcomb-form complains:

```
/overview/content is `123` should be a `Str`
```

Why wouldn't the user-typed value of 123 register as a string? Because the TextBox transform converts that into a number:

```
    transformer: Object.freeze({
      format: function (value) {
        return Nil.is(value) ? null : value;
      },
      parse: parseNumber
    }),
```

```
function parseNumber(value) {
  var n = parseFloat(value);
  var isNumeric = (value - n + 1) >= 0;
  return isNumeric ? n : value;
}
```

I think this is a bug, it shouldn't get converted to a number just because it looks like one.

I'm using 0.4.10 BTW.

**Comment by gcanti** [comment]
Hi,
yes it's a bug introduced in the 0.4.9 -> 0.4.10 refactoring. It should be fixed in the last 0.4.11 release.
