### ISSUE TITLE
Bind error text to field type

### ISSUE THREAD

**Issue by liuyang1204** [gcanti/tcomb-form#115]
Sometimes it is more intelligent to bind error text to field type.

E.x. for all fields of type 'email', the error text:

```
Invalid email format
```

for all fields of type 'password', the error text:

```
Password should contains at least 1 upper case letter, ...
```

Is there a way to do this currently? I don't want to set error text on every field, one by one.

More over, could one field have different kinds of error? (this might be another issue)

E.x. If the field is empty, firstly show `This field is required`, after it is filled, we may show `format is incorrect`.

**Comment by gcanti** [comment]
> I don't want to set error text on every field, one by one.

Being `options` a POJO, you could generate it to fit your use cases.

> More over, could one field have different kinds of error?

The `error` option can also be a function with the following signature:

```
(value: any) => ?(string | ReactElement)
```

where `value` is the current field value, so you can return the proper error message.

**Comment by liuyang1204** [comment]
Thanks for response!

Well, now I understand I could have some way to do it, but not clean, in my feeling.

I found the following example about a 'subtype'.

```
// a type representing positive numbers
var Positive = t.subtype(t.Num, function (n) {
  return n >= 0;
});

var Person = t.struct({
  name: t.Str,
  surname: t.Str,
  email: t.maybe(t.Str),
  age: Positive // refinement
});
```

I feel it quite clear & fit if we could write something like:
```
var Positive = t.subtype(t.Num, function (n) {
  return {
    valid: n >= 0,
    error: 'should be positive number'
  };
});
```
In this way, we clearly define the `validation rules` with the `error text if the rule fails` together. And it fits a validation chain perfectly with the chain of type inheritance.

Required type        |      ->        |     Num         |          ->                |               Positive
---------------------------|--------|-----------|---------|--------------
Should not be empty |-> |Should be a number |-> | should be positive number

**Comment by gcanti** [comment]
Attaching the error messages to type definitions can raise issues:

- `subtype` is a tcomb's API, so the function must be a predicate
- internationalization: changing locale would mean to re-define the type

Btw, if you define subtypes, since all tcomb's types carry meta infos (in the `meta` object attached to the constructor) you could easily generate the `options` POJO using runtime type introspection.
