### ISSUE TITLE
checkbox group

### ISSUE THREAD

**Issue by bieg** [gcanti/tcomb-form#117]
Hey there

Awesome piece of work you have delivered! I looked everywhere but is it possible to create a checkbox group? I had difficulties with this as they are rendered as booleans.

looking forward to your answer.

Cheers

Wouter

**Comment by gcanti** [comment]
Closing in favour of 118

**Comment by bieg** [comment]
Sorry. Hit enter twice...

**Comment by gcanti** [comment]
No problem ;-)

**Comment by bieg** [comment]
It's really great this support on this feature - nothing gets unnoticed :)-
