### ISSUE TITLE
How create a radio group?

### ISSUE THREAD

**Issue by bieg** [gcanti/tcomb-form#118]
Hey there

Awesome piece of work you have delivered! I looked everywhere but is it possible to create a checkbox group? I had difficulties with this as they are rendered as booleans.

looking forward to your answer.

Cheers

Wouter

**Comment by gcanti** [comment]
Hi, thanks.
If you mean a group of radio buttons see https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#render-as-a-radio-group

**Comment by bieg** [comment]
Yes!! That is exactly what I need ;)

**Comment by johnraz** [comment]
@gcanti : do we have a solution for checkbox groups? 
radio group is meant to reflect a select while checkbox group should reflect a multi select.

**Comment by gcanti** [comment]
a struct of boolean fields?

**Comment by johnraz** [comment]
I need them to have the same name is it allowed ?

**Comment by johnraz** [comment]
Ok I did a bit more feedling around and your answer covers my need again :-) 

Didn't realize nesting struct would give me a way to group booleans together !  
Thanks for the help again !

**Comment by johnraz** [comment]
@gcanti, I still have 2 small things that bothers me and that are not solved by the struct of boolean fields:

* The nested struct implies a fieldset, which in my case is not what I need. I need a regular label, overridable by the configuration. Is it possible with the struct ? 

* Each boolean field ends up in a bootstrap `form-group`, they should ideally be in the same `form-group`.

Any direction on how to achieve this ? I'm willing to contribute if needs be ;-)

**Comment by gcanti** [comment]
> I need a regular label, overridable by the configuration. Is it possible with the struct ?

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#legend ?

> Each boolean field ends up in a bootstrap form-group, they should ideally be in the same form-group.

You could write a custom template for that struct

**Comment by johnraz** [comment]
> https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#legend ?

This will solve the label override but not the design applied by bootstrap for fieldsets, which I don't want.

> You could write a custom template for that struct
I will look into creating a custom template ;-)

Thx !
