### ISSUE TITLE
Left align lable text in horizontal forms (bootstrap skin)

### ISSUE THREAD

**Issue by bieg** [gcanti/tcomb-form#119]
Hey Giulio

Do you know how I can get my label text set to left align?
I have tried a few things but just did not get far.

much obliged!

Wouter

**Comment by gcanti** [comment]
Do you mean bootstrap horizontal forms? There's an option https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#struct

Otherwise could you provide an example / snippet / result of what you want to achieve?

**Comment by bieg** [comment]
Thanks for replying so quickly.
YEs I am using that in my project however the label text is right aligned.  How do I get it to left align?

**Comment by gcanti** [comment]
Ah sorry, I misread your first comment. It's not possible at the moment. Is there an idiomatic way with bootstrap to do that?

http://getbootstrap.com/css/#forms-horizontal

**Comment by gcanti** [comment]
I'd tweak the stylesheet: what about overriding the `.form-horizontal .control-label` style?
