### ISSUE TITLE
Customising date input

### ISSUE THREAD

**Issue by bieg** [gcanti/tcomb-form#120]
I am using t.forum.dat but noticed the lastfield (year) isn't a Dropdown but an unlimited textbook.
Why is that? How do I getting to display a list of years in that last column instead?

Thanks a lot!

Wouter

**Comment by bieg** [comment]
Pardon the description. 
(using mobile;)

I am using t.forum.dat but noticed the lastfield (year) isn't a Dropdown but an unlimited textbook.
Why is that? How do I getting to display a list of years in that last column instead? 

Thanks a lot!

Wouter

**Comment by bieg** [comment]
Sorry I see some typo's. 
But the last field with t.form.dat has an input field instead of a drop down box. 
Why is that?

**Comment by gcanti** [comment]
That is just the default implementation. In my use case I don't want to impose constraints to the user.
You can customise the input component writing a custom template (overriding the default one https://github.com/gcanti/tcomb-form/blob/master/src/templates/bootstrap.js#L431)
or even writing your own input component.
