### ISSUE TITLE
this.refs.form.getComponent is no longer working?

### ISSUE THREAD

**Issue by aaronksaunders** [gcanti/tcomb-form#121]
testing with latest release and sample app and getting red screen
```
this.refs.form.getComponent is not a function
```
is there a new way to get the underlying component

**Comment by gcanti** [comment]
Weird, the API is still there
https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L688

**Comment by aaronksaunders** [comment]
my bad, I logged this in the wrong place... moving to tcomb-form-native
