### ISSUE TITLE
How can i set a buttonAfter?

### ISSUE THREAD

**Issue by snadn** [gcanti/tcomb-form#126]
when i set `addonAfter`, it add `.input-group-addon`. 
And how can i add `.input-group-btn`.

**Comment by gcanti** [comment]
I'ts not supported at the moment. I'll try to add it

**Comment by snadn** [comment]
thanks

**Comment by snadn** [comment]
Why only support buttonAfter. buttonBefore is the same ah...
![image](https://cloud.githubusercontent.com/assets/1269858/7568436/62ece084-f835-11e4-923b-a64ba9126af4.png)

**Comment by gcanti** [comment]
> buttonBefore is the same

Added to v0.5.3
