### ISSUE TITLE
Error when compiling 0.5.1 example with babel

### ISSUE THREAD

**Issue by ilmattodel93** [gcanti/tcomb-form#127]
Hi, first of all I would like to thank you for your awesome tcomb library suite!

I don't understand why when I compile with requirejs the first full example of the 0.5 doc I get an invariant exception.

This is my build script:

http://pastebin.com/XWQi1n7E

Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.invariant @ invariant.js:42ReactOwner.addComponentAsRefTo @ ReactOwner.js:70attachRef @ ReactRef.js:23ReactRef.attachRefs @ ReactRef.js:39attachRefs @ ReactReconciler.js:22assign.notifyAll @ CallbackQueue.js:68ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:81Mixin.closeAll @ Transaction.js:207Mixin.perform @ Transaction.js:148batchedMountComponentIntoNode @ ReactMount.js:269Mixin.perform @ Transaction.js:134ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:66batchedUpdates @ ReactUpdates.js:110ReactMount._renderNewRootComponent @ ReactMount.js:404ReactPerf.measure.wrapper @ ReactPerf.js:70ReactMount.render @ ReactMount.js:493ReactPerf.measure.wrapper @ ReactPerf.js:701.react @ test.js:38s @ _prelude.js:1e @ _prelude.js:1

**Comment by ilmattodel93** [comment]
I mistyped, i meant browserify

**Comment by gcanti** [comment]
Hi, thanks!

> Invariant Violation: addComponentAsRefTo(...)

Maybe:

https://github.com/gcanti/tcomb-form/issues/111
https://github.com/gcanti/tcomb-form/issues/107

?

**Comment by ilmattodel93** [comment]
Thanks, in fact i noticed that I had a different react version in the global module folder, and it was loading react twice!

Thanks for support!

**Comment by pingyuanChen** [comment]
Hey @ilmattodel93, How did you find the different react version, I got same problem, and I use babel and browserify.
