### ISSUE TITLE
version conflicts

### ISSUE THREAD

**Issue by chasm** [gcanti/tcomb-form#132]
npm ERR! peerinvalid The package tcomb-form does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tcomb-react@0.2.4 wants tcomb-form@^0.4.5

Can this be corrected? I'm having a heck of a time using the tcomb libraries together, or with the latest react. What can I do to help?

**Comment by gcanti** [comment]
> Can this be corrected?

Sure. Thanks for pointing out. I'll release a compatible version of tcomb-react asap.

Closing in favour of https://github.com/gcanti/tcomb-react/issues/7
