### ISSUE TITLE
Unable to disable t.Dat field

### ISSUE THREAD

**Issue by sogko** [gcanti/tcomb-form#137]
Given the following model and options, I was unable to disable the Date field.
The `disabled` option worked for t.Str / text field though.

Thanks!

```javascript
var model = t.struct({
   text: t.Str,
   date: t.Dat
});
var options = {
  fields: {
    text: {
      disabled: true
    },
    date: {
      disabled: true
    }
  }
};
```

**Comment by gcanti** [comment]
Good catch, thanks

**Comment by Aadesh05** [comment]
Whats the solution how to disable the field ?
