### ISSUE TITLE
Update guide for v0.5.4 ?

### ISSUE THREAD

**Issue by mwise** [gcanti/tcomb-form#141]
Hello,

Are you planning to update the guide for v0.5.4? I am trying to incorporate this library, but am having difficulty reconciling the guide with v0.5.4. Specifically, the Transformers section with the search query split on spaces doesn't work. It seems that the List component constructor blows up when you attempt to use a Transformer to convert the values as described in the Transformers section.

Since I've never used this library before, it's hard to know what in the guide is accurate for the current version and consequently pretty hard to do anything beyond the basic rendering of form elements. `tcomb` proper works like a champ, though :-)

Cheers,
Mark

**Comment by gcanti** [comment]
Hi Mark,
I just added a "Transformers" section to the guide (v0.5.4 compatible):

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#transformers

Let me know if it works for you.

Giulio

**Comment by mwise** [comment]
Yep, we were able to get it working right as you posted this reply, heh. The confusing part about the 0.4 docs was that it seemed to use the custom search template in the Transformers guide section. Thanks for the quick reply!

**Comment by gcanti** [comment]
:+1:
