### ISSUE TITLE
Checkbox groups

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb-form#142]
Curious how I might implement a checkbox group. My current approach –– a struct of Bools is not looking pretty. 

```
var Holidays = t.struct({
  "New Year's Day": t.Bool,
  "MLK Birthday": t.Bool,
  'Presidents Day': t.Bool,
  "Memorial Day": t.Bool,
  "Independence Day": t.Bool,
  "Labor Day": t.Bool,
  'Christmas Day': t.Bool,
  'Other': t.Bool
})
```

I guess this is a job for custom factories?

**Comment by gcanti** [comment]
That's how I would implement it.

> is not looking pretty

Why? I mean, you are speaking of the result in the UI or you don't like so may fields in the struct?

**Comment by volkanunsal** [comment]
The main requirement for me is that `holidays` field should look like any other field, but when I use a `struct`, it looks like a fieldset –– i.e. the `label` becomes a legend. I have to modify the template of the field to make it work, but this is a fragile solution –– if the form's horizontal layout configurations change down the line, I have to update the template, too. 

So, a `CheckboxGroup` component would ideally allow me to specify a struct and return it as a regular field. This may or may not be a feature request. :)
