### ISSUE TITLE
Dependent subtypes

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb-form#143]
Is there any example of how to implement a dependent subtype? E.g.

```
var THourlyRate = t.subtype(t.Num, (n)=>{ return n > 9 })

//Must be be at least twice the THourlyRate
var TOvertimeRate = t.subtype(t.Num, (n)=>{ ... })
```

**Comment by gcanti** [comment]
A dependent type is a type that depends on a value, that is a **family** of types:

```js
function dependent(a) {
  return subtype(t.Num, n => n >= 2 * a);
}
```

It's not what you want to achieve I guess.

I may be way off base on this, but if you want to keep a strict relation between 2 values, we are speaking of a subtype of a cartesian product. What about a subtype of a struct or of a tuple?

```js
var THourlyRate = t.subtype(t.Num, n => n > 9);

var CartesianProduct = t.subtrype(t.struct({
  hourlyRate: THourlyRate,
  overtimeRate: t.Num
}), s => s.overtimeRate >= 2 * s.hourlyRate);

// or

var CartesianProduct = t.subtrype(t.tuple([
  hourlyRate: THourlyRate,
  overtimeRate: t.Num
]), s => s.overtimeRate >= 2 * s.hourlyRate);
```

**Comment by volkanunsal** [comment]
You're right about dependent types. I wasn't thinking of it like that.

I see what you're saying here. I'm going to give it a try. :)

**Comment by volkanunsal** [comment]
Ok, I just tried this out. It's definitely working, in that the form appears to be invalid when the `overtime_rate` is less than twice the regular rate. 

However, there are two problem with this approach. By using a `struct`, the fields are placed in a new namespace, e.g. `<input name='payment[overtime_rate] />'`. 

Second, the form appears valid, even though it's not. There are no validation errors in sight. The payment `fieldset` doesn't receive the `has-error` class.

**Comment by gcanti** [comment]
> The payment fieldset doesn't receive the has-error class

Yes, otherwise all the fields would be red. You could provide a custom error message though

```js
var THourlyRate = t.subtype(t.Num, n => n > 9);

var Payment = t.subtype(t.struct({
  hourlyRate: THourlyRate,
  overtimeRate: t.Num
}), s => s.overtimeRate >= 2 * s.hourlyRate);

var options = {
  error: 'my custom error message'
};
```

**Comment by volkanunsal** [comment]
I tried that, but the error message didn't get cleared when the fields became valid again. Seems like the error callback is only called when there is an error, which makes sense...
