### ISSUE TITLE
Hidden for select ? 

### ISSUE THREAD

**Issue by johnraz** [gcanti/tcomb-form#145]
Select doesn't seem to be supporting the `hidden` option, am I missing something ? 

If not, do you have an opinion about this ?

**Comment by gcanti** [comment]
> Select doesn't seem to be supporting the hidden option

Yes it's not supported.

> If not, do you have an opinion about this ?

Well, it depends on what you want to achieve. If you just want do not show the component you could use the `t.form.Textbox` factory:

```js
var Gender = t.enums({
  M: 'Male',
  F: 'Female'
});

var Person = t.struct({
  name: t.Str,
  gender: Gender
});

var options = {
  fields: {
    gender: {
      factory: t.form.Textbox,
      type: 'hidden'
    }
  }
};

var value = {
  gender: 'Male' // sets the default value which won't be changed by the user 
}
```

**Comment by johnraz** [comment]
Yes the factory trick should do it ! Thanks a lot.  

Any idea on how I could reference the factory dynamically ? 
My options are generated server side at the moment as a json object, factories are the only part left I can't map :)

**Comment by johnraz** [comment]
Nevermind my last comment I will put it in a separate json object and deal with it in my own code ;-)
