### ISSUE TITLE
Ordering fields in nested forms

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb-form#147]
I need to order dynamically added fields on a nested form and finding that the order field is not working within the nested form field options. I wonder if this option can only be specified at the top-level or if I am doing something wrong? 

My form configuration looks kinda like this:

```javascript
let room_fields = t.struct({
  room_size: t.Num
});

if(room.working_heat){   
  room_fields = room_fields.extend({
    heat_controlled: t.Bool 
  })
}
let Page4 = t.struct({
  // other fields here
  room: room_fields
});

let Page4Options = {
  fields: {
    room: {
      order: ["heat_controlled", "room_size"]
      // ....
    }
  }
}
```

**Comment by gcanti** [comment]
> I wonder if this option can only be specified at the top-level 

No, and after a test it does work for me. What do you see in the UI?

**Comment by volkanunsal** [comment]
In the UI, the order is maintained until I remove the template function:

```javascript
template: function(locals){
  return <div>
    {React.addons.createFragment(locals.inputs)}
  </div>
}
```

Only then the `order` property becomes effective.

**Comment by volkanunsal** [comment]
Hm, actually, that wasn't a factor. It just doesn't work.

**Comment by volkanunsal** [comment]
No, wait, it was a factor. Yes, the template function is overriding the order property.

**Comment by gcanti** [comment]
so you are using a custom template...

now it's clear what's happening: in `locals.order` you'll find your `["heat_controlled", "room_size"]` array.
If you write a template is up to you to code the features provided by the default templates (in this case ordering).

**Comment by volkanunsal** [comment]
Makes sense. Let me see what I can do with that.

**Comment by volkanunsal** [comment]
The more I work with this library, the more impressed I become. I just wanted to say thank you @gcanti for building this beauty.

**Comment by gcanti** [comment]
I spent countless hours writing this library, what you are saying means a lot to me. Thanks
