### ISSUE TITLE
Input control customize template

### ISSUE THREAD

**Issue by scoarescoare** [gcanti/tcomb-form#148]
I referred to #37 and #8, not sure if they're exactly the same.

What's the easiest way to alter the template of a textobx?

Here's what it currently renders for the `name` property of my model.
```html
<div class="form-group form-group-depth-1">
    <label class="control-label">Name</label>
    <input name="name" type="text" class="form-control" >
</div>
```

But I want this:

```html
<div class="form-group form-group-depth-1">
    <label class="control-label">Name</label>
    <div class="something-else">
        <input name="name" type="text" class="form-control" >
    </div>
</div>
```

I suspect that it's not super trivial to do this from looking at the the other issues above. I saw an example here http://gcanti.github.io/tcomb-form/guide/index.html#custom-components but not sure if I want to fully implement a new component just to alter the template.

Thanks

**Comment by gcanti** [comment]
Hi, here an example:

```js
var Person = t.struct({
  name: t.Str
});

function mytemplate(locals) {
  // console.log(locals); // <= inspect the "recipe" for your textbox provided by tcomb-form
                          // keep in mains that now it's up to you now 
                          // to provide all the features of the default template

  // handle value changes
  function onChange(evt) {
    locals.onChange(evt.target.value);
  }

  // handle errors
  let className = `form-group form-group-depth-${locals.path.length}`;
  if (locals.hasError) {
    className += ' has-error';
  }

  return (
    <div className={className}>
      <label className="control-label">{locals.label}</label>
      <div className="something-else">
          <input name="name" type="text" className="form-control" value={locals.value} onChange={onChange} />
      </div>
    </div>
  );
}

var options = {
  fields: {
    name: {
      template: mytemplate
    }
  }
};
```

**Comment by scoarescoare** [comment]
Ok great that makes sense to me. 

> keep in mind that now it's up to you now to provide all the features of the default template

Out of curiosity, where exactly is the default template for the textbox? I see that the textbox is wrapped with `decorator.template('textbox')` but what exactly does that mean and how does  it get provided [here](https://github.com/gcanti/tcomb-form/blob/6b3d72412236354af8e01c8eb14456bf24df431e/src/components.js#L71)?

Thanks for assisting me so quickly!

**Comment by gcanti** [comment]
The default template for the textbox is here:

https://github.com/gcanti/tcomb-form/blob/master/src/templates/bootstrap.js#L144

It's written with the help of uvdom (https://github.com/gcanti/uvdom) instead of jsx so..it's not exactly readable :)
