### ISSUE TITLE
Bootstrap columns

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb-form#149]
Is it strictly necessary to ensure the Bootstrap columns add up to 12?

https://github.com/gcanti/tcomb-form/blob/master/src%2Ftemplates%2Fbootstrap.js#L15

I sometimes need the right column to be small in order to make the input field match the expected input size. Can this requirement be relaxed?

**Comment by gcanti** [comment]
> Can this requirement be relaxed?

Sure

**Comment by volkanunsal** [comment]
I noticed something strange is happening. The column `a` is expanding to 12 - `b` columns in width. If I make one column 0 and the other 8, the first column automatically becomes 4 wide.

**Comment by gcanti** [comment]
weird, with the following configuration:

```js
const options = {
  config: {
    horizontal: {
      lg: [2, 2]
    }
  }
};
```

I can see both the two columns with `className="col-lg-2"`
