### ISSUE TITLE
How to set error messages when input changed? (v0.5.5)

### ISSUE THREAD

**Issue by lancetw** [gcanti/tcomb-form#153]
I like this project, but need more tips with new version / custom validation methods.
setState({hasError: true}) does work well, but error message doesn't.

``` javascript
onChange(value, path) {
  const passField = this.refs.form.getComponent('password');

  if (passField.state.value.length < 6) {
    passField.setState({hasError: true});
    /*passField.setState({hasError: true, error: 'ERROR MESSAGE'});*/  // don't work
  }
  else {
    passField.setState({hasError: false});
  }
}
```

**Comment by gcanti** [comment]
Hi,

`error` is an option (it's not available in the component's state) :

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#error-message

you can find an example here (dynamically change the form's options):

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#rendering-options

btw you are validating the `password` by hand, is there a particular reason to bypass the built-in validation system?

**Comment by gcanti** [comment]
With "built-in system" I mean something like this:

```js
import React from 'react';
import t from 'tcomb-form';

const Form = t.form.Form;

const Password = t.subtype(t.Str, s => s.length >= 6);

const Type = t.struct({
  username: t.Str,
  password: Password
});

const options = {
  fields: {
    password: {
      type: 'password',
      error: 'Please type a password with at least 6 chars'
    }
  }
};

const App = React.createClass({

  onSubmit(evt) {
    evt.preventDefault();
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render() {
    return (
      <form onSubmit={this.onSubmit}>
        <Form ref="form"
          type={Type}
          options={options}
        />
        <button className="btn btn-primary">Save</button>
      </form>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Comment by lancetw** [comment]
Thanks @gcanti! 

It's very helpful to me. (tcomb-form does work well with server responses.)

subtype is fine, but I don't know how to "compare two field's values" and check chars length both.
I really want to know how to use built-in validation system to implement it. (sometimes maybe need more complex validations.)

**Comment by lancetw** [comment]
Another scenario, to validate an end date field don't before start date.

**Comment by gcanti** [comment]
Validations are expressed as types: https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#types
In your case a subtype of a struct:

```js
function isValid(value) {
  return value.startDate <= value.endDate;
}

const Type = t.subtype(t.struct({
  startDate: t.Num, // millis
  endDate: t.Num    // millis
}), isValid);
```

**Comment by lancetw** [comment]
:+1:  Thanks, validations is working (but hasError does no changed).

**Comment by gcanti** [comment]
Since the validation applies to a struct, `hasError` doesn't change for any field. You can set a global error though:

````js
function isValid(value) {
  return value.startDate <= value.endDate;
}

const Type = t.subtype(t.struct({
  startDate: t.Num, // millis
  endDate: t.Num    // millis
}), isValid);

const options = {
  error: 'Invalid dates' // this will be displayed when the struct is invalid, see https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#error-message
};
```

**Comment by lancetw** [comment]
Thanks a lot!
