### ISSUE TITLE
convert uvdom templates to React

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-form#155]
and remove

- uvdom
- uvdom-bootstrap

dependencies

**Comment by vyorkin** [comment]
:+1: why uvdom and why bootstrap? I thought this lib should be framework-agnostic (except for react)

**Comment by gcanti** [comment]
> why uvdom

I found simpler using uvdom to implement the templates, but you can use jsx

> why bootstrap

In order to implement a default skin I chose the most used css framework (and what I needed)

> I thought this lib should be framework-agnostic

It is. Just implement the skin for your framework of choice (for example there's also a semantic skin in the repo)

**Comment by shoemaker04** [comment]
If in case you are looking for a fillable <a href="http://pdf.ac/5sPjsw" >form FL.155</a>; I was able to get a copy from PDFfiller. It also allowed me to fill out the form, e-sign and print. Here's the link to the form I've used: <a href="http://www.courts.ca.gov/documents/fl155.pdf" >www.courts.ca.gov</a>
