### ISSUE TITLE
Two children with the same key when using template

### ISSUE THREAD

**Issue by evax** [gcanti/tcomb-form#157]
I'm having the same issue as #152, but I'm using a template.
Moreover, when using nested structs, only the first field of the nested struct will display.
Everything works properly without the template.

**Comment by gcanti** [comment]
- v0.5.5?
- please could you put up a gist with your code or a minimal example so that I can reproduce the issue?

**Comment by evax** [comment]
yes, v0.5.5
I'll create a gist now.

**Comment by gcanti** [comment]
> I'll create a gist now.

Thanks!

**Comment by evax** [comment]
Trying to build a minimal failing example is enlightening, and allowed me to find these issues so far in my code:
 - the 'first field only' issue was caused by specifying the template as `templates: {struct: myTemplate}` instead of just `template: myTemplate` (this used to work but broke of course when I introduced nested structs)
 - my nested struct fields options where misplaced: I had `fields: {nestedStructList: {fields: {...}}}` instead of `fields: {nestedStructList: {item: {fields: {...}}}`

With this in place I can get things to work, but it breaks again if I remove the `nestedStructList` fields entry, and I couldn't yet reproduce this in the minimal test case.

**Comment by gcanti** [comment]
Closing in favour of #152
