### ISSUE TITLE
Field-aware validation/invalidate specific fields

### ISSUE THREAD

**Issue by RedRoserade** [gcanti/tcomb-form#158]
Is it possible to validate a field's value based on the value of another field?

For example, consider the following `struct`:
```javascript
const MyStruct = t.struct({
  StartDate: t.Dat,
  EndDate: t.subtype(t.Dat, d => d <= new Date()),
  // Other fields
});
```

I don't want `EndDate` to be in the future, but I also don't want `StartDate` to be posterior to `EndDate`. 

I could do something like this:
```javascript
const MyStruct = t.subtype(t.struct({
  StartDate: t.Dat,
  EndDate: t.subtype(t.Dat, d => d <= new Date()),
  // Other fields
}), s => s.StartDate <= s.EndDate);
```

This works, I've done it a couple of times. However, this doesn't allow me to say 'Only `StartDate` is wrong', so what I end up doing is this:

```javascript
// Other react component's code
getModel() {
  return t.struct({
    StartDate: t.subtype(t.Dat, d => d <= this.state.value),
    EndDate: t.subtype(t.Dat, d => d <= new Date()),
    // Other fields
  });
}
render() {
  return (
    <Form type={this.getModel()} value={this.state.value}
      onChange={v => this.setState({ value: v })} />
  );
}
```

This does allow me to invalidate the field properly, but I then have to turn the `<Form />` into a controlled component, and this doesn't work if the `struct` that is to be validated is in a `list`, because, how can I then know which `StartDate` is to be validated?

A possible solution to this would be to pass the current value of the parent `struct` to the validation function, either via `this` or by other arguments in the validation function passed to `subtype()`:

```javascript
const MyStruct = t.struct({
  StartDate: t.subtype(t.Dat, (date, parent) => date <= parent.EndDate), // parent would be a representation of MyStruct
  EndDate: t.subtype(t.Dat, d => d <= new Date()),
  // Other fields
});
```

**Comment by gcanti** [comment]
> A possible solution to this would be to pass the current value of the parent struct to the validation function, either via this or by other arguments in the validation function passed to subtype():

In `tcomb`, refinements are defined with a predicate `(x: any) => boolean`. I can't change this signature in favour of specific tcomb-form requirements.
