### ISSUE TITLE
Hiding Label

### ISSUE THREAD

**Issue by sean-madhavan** [gcanti/tcomb-form#160]
I want to hide label and use placeholder instead for textboxes. Is it possible to do it without overriding template?

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#automatically-generated-placeholders

```js
// form rendering options
var options = {
  auto: 'none', // do not generate automatic labels nor automatic placeholders
  fields: {
    mytextbox: {
      attrs: {
        placeholder: 'myplaceholder' // set the textbox placeholder
      }
    }
  }
};
```

**Comment by sean-madhavan** [comment]
Thanks @gcanti ! It was what I was looking for. :+1: 
Should have read struct section.
