### ISSUE TITLE
Tabbed list

### ISSUE THREAD

**Issue by a58az** [gcanti/tcomb-form#165]
Hello, I'm newbie in tcomb-form and react.

Can I make tabs for list, becasuse I can have tens or event hundrends items in a list. So can I use bootstrap tabs(http://getbootstrap.com/javascript/#tabs) and if I can, how I can do it?

I suppose I can use templates, but I have no idea, how can I make this tabs.

Simmilar thing have json-editor wich works with json-schema. [example](http://jeremydorn.com/json-editor/?schema=N4IgLgngDgpiBcICGAnFSIgDQgGYHsUBbJMBcJAIwGdtwBLMAGzkQAUYxacBXAO3oBHHjACSYGEVrwwKETkaTpoSLHL5KAKxgBjMjjCMW5DvpBQU+WCkMxl4aKxWPy1WfT4BzOjD48iCADaIDqkdAAm+N44lPQo4XQoMFCGxjj4YAAWMCggALo44TC4SDxMZIiR3gC+OHxIRE4OaohuKB411bUgRSVlFYHOLT1RdPWN5ADqSOU5INV51UAA=&value=NobwRALgngDgpmAXGAJgewOZgDRgHYCGAtgsgOoEA2EcATmAL7bjTxKqY77GliPORYvdFlyES7fiyHsRXcbymC2yOWJ6Sm0lR1HcJyRgF0gAAA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

**Comment by gcanti** [comment]
> I suppose I can use templates

I guess you should define a react component handling your tabs and then wrap it in a tcomb-form custom-template
