### ISSUE TITLE
Submit on keydown - enter

### ISSUE THREAD

**Issue by skrobek** [gcanti/tcomb-form#167]
I wanted to keep default functionality for forms. Is there a way to bind `keyDown` event to the wole from ? It dosen't matter on which input user will be focused. Always when user hits enter, form should be submited.

**Comment by gcanti** [comment]
The easiest way I found is wrapping the form with a `form` tag, add a submit button, and then let the browser do its job

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#submitting-the-form

**Comment by skrobek** [comment]
Now I see. Is there said explicitly that `<Form>` doesn't create a form tag ?

**Comment by gcanti** [comment]
Yep

> The output of the Form component is a fieldset tag containing your fields. You can submit the form wrapping the output with a form tag

**Comment by skrobek** [comment]
Ok. Thank you for help and information ;-)

**Comment by gcanti** [comment]
You're welcome ;-)
