### ISSUE TITLE
Customize enum template

### ISSUE THREAD

**Issue by johnraz** [gcanti/tcomb-form#168]
Hi there,

I would like to add a button next to a `select` build from a `t.enums`. This button should change its behavior depending on the selection made.

From what I've read so far, I understand that we can override a template by defining the `template` key in the `options` object. So far, so good, I made it work.

My issue is that I can't find a way to easily re-use the default `select` template in order to actually display the `select` element.

Copy-pasting the all `t.form.Form.templates.select` function works but it seems overkill and cumbersome to have to duplicate so much code to only append a button.

Am I missing something or is this the only way ?

I also read a bit about factories but I have to admit that I'm kinda confused on how it would better solve my issue or not.

Thanks already.

**Comment by gcanti** [comment]
Well there's an alternative I can think of...
The default templates are written in [UVDOM](https://github.com/gcanti/uvdom) so the `select(locals)` function returns simply an object (which later is transformed to react elements). If it's your cup of tea, you could modify / transform / amend / cherrypick that uvdom at runtime. Example:

```js
import React from 'react';
import t from 'tcomb-form';
import { select } from 'tcomb-form/lib/templates/bootstrap';

function template(locals) {
  const uvdom = select(locals);
  
  // console.log(uvdom); // this will show the current uvdom tree

  //
  // customize the template adding a button
  //

  uvdom.children.push({
    tag: 'button',
    children: 'my button',
    events: { // add an event handler
      click: function () {
        evt.preventDefault();
        alert('You clicked me!');
      }
    }
  });

  return uvdom;
}

const Country = t.enums.of('IT US');

const Type = t.struct({
  country: Country
}, 'Type');

const options = {
  fields: {
    country: {
      template
    }
  }
};

const App = React.createClass({

  onSubmit(evt) {
    evt.preventDefault();
    const value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render() {
    return (
      <form onSubmit={this.onSubmit}>
        <t.form.Form
          ref="form"
          type={Type}
          options={options}
        />
        <button className="btn btn-primary">Save</button>
      </form>
    );
  }

});
```

**Comment by johnraz** [comment]
First of all, I want to stress out how amazed I'm with the fast , meaningful and exhaustive responses I always get from you regarding those projects, I can't say much more than thanks.

Next, if I wan't to stick with jsx syntax, am I right to think that I can use the `"uvdom/react"` `compile` function to get back the react elements ?

**Comment by gcanti** [comment]
You're welcome, truth is I had so much fun writing these libraries that I'm glad to have an occasion to explain my choices and the internals.

> if I wan't to stick with jsx syntax, am I right to think that I can use the "uvdom/react" compile function to get back the react elements ?

- Side note. you can insert jsx inside an uvdom (but not the other way around):

```js
function template(locals) {

  function onClick(evt) {
    evt.preventDefault();
    alert('You clicked me!');
  }

  const uvdom = select(locals);
  
  // jsx instead of uvdom
  uvdom.children.push(<button onClick={onClick}>You clicked me!</button>);

  return uvdom;
}
```

- the "uvdom/react" compile function is what tcomb-form uses to get back the react elements:

import:

https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L5

usage:

https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L236

**Comment by johnraz** [comment]
Ok doing something like this worked:

```javascript
var scheduleTemplate = function (locals) {
  console.log(uvdom.react);
  var reactSelect = uvdom.react.compile(t.form.Form.templates.select(locals));
  console.log(reactSelect);
  return (
      <div>
        {reactSelect}
        <a href="#">Click me</a>
      </div>

  );
};
```

Thanks again for the feedback !

**Comment by gcanti** [comment]
:+1:
