### ISSUE TITLE
I18n fields label

### ISSUE THREAD

**Issue by a58az** [gcanti/tcomb-form#170]
Hello, Can I translate labels? 
I want something like this
`export var en = {
    optional: "Optional",
    add: "Add",
    remove: "Remove",
    up: 'Up',
    down: 'Down',
    name: "Name"
};`

where name it's one of my fields
`export var Example = t.struct({
    name: t.Str,
    secondName: t.maybe(t.Str),
    lastName: t.Str
});`

**Comment by gcanti** [comment]
Not sure I'm follow, translate labels of what? This:

```js
export var en = { optional: "Optional", add: "Add", remove: "Remove", up: 'Up', down: 'Down' };
```

seems the i18n bundle for lists but you have a struct.
Could you elaborate a little bit on your use case?

**Comment by a58az** [comment]
I want using something like i18n for list, but using it for struct.

For example I have a form:
Name: _______

And after click on some button (not important how exactly it will work) I want translate it. So in result we will see (translation to french):
Nom: _______

**Comment by gcanti** [comment]
You can override the default label with the label option:

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#label

**Comment by a58az** [comment]
Any other method? In options I have many other things and I want separate it from translations.

And one more question, how can I disabled fields which contains in list (maybe I need create another issue for that question?).

`var Example = t.struct({
    name: t.Str,
    secondName: t.maybe(t.Str),
    lastName: t.Str,
    cars: t.list(Car)
});

var Car = t.struct({
    number: t.Num, //  must be disabled (read-only)
    maker: t.String,
    model: t.String
});
`

**Comment by gcanti** [comment]
> Any other method? In options I have many other things and I want separate it from translations

`options` are simply POJOs, you could build them in a smart way keeping different concerns separated

> how can I disabled fields which contains in list

```js
var Car = t.struct({
  number: t.Num, // must be disabled (read-only)
  maker: t.String,
  model: t.String
});

var Example = t.struct({
  name: t.Str,
  secondName: t.maybe(t.Str),
  lastName: t.Str,
  cars: t.list(Car)
});

const options = {
  fields: { // here the Example configuration
    cars: { // here the list configuration
      item: { // options for each element in the list
        fields: {
          number: {
            disabled: true
          }
        }
      }
    }
  }
};
```
