### ISSUE TITLE
Passing the field identifier as classname

### ISSUE THREAD

**Issue by johanneslumpe** [gcanti/tcomb-form#171]
Is there a way to pass a classname in the form of `field-FIELDNAME` to the fields and `fieldset-STRUCTNAME` to the fieldsets? That would be really useful for styling purposes. I know I can solve this by writing my own template, but I'd like to avoid copying the whole semantic template, just in order to add these classes (which might still be a problem, due to structs not receiving their own key via locals), which I feel somehow belong in there by default. Thoughts?

**Comment by gcanti** [comment]
Hi,
For fields you can set a `className` attribute:

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#styling

**Comment by johanneslumpe** [comment]
@gcanti yes, but i want them on the wrapping div, not on the input itself :)

**Comment by gcanti** [comment]
Oh ok, now I understand. I'll think about it. 
In the meanwhile you could enhance the default templates without copying them, see this issue:

https://github.com/gcanti/tcomb-form/issues/168

**Comment by gcanti** [comment]
Released in [v0.7.7](https://github.com/gcanti/tcomb-form/releases/tag/v0.7.7)
