### ISSUE TITLE
Form value isn't updated when state changes

### ISSUE THREAD

**Issue by jonaswindey** [gcanti/tcomb-form#173]
I have a state (loaded via flux) that changes when the component receives new props (another id is passed to the form)

However, the form value isn't updated when the state changes. It only works on the initial render.
```
{this.state.formValue.company} -> this is always correctly updated
<Form type={model.Model}
   ref="form"
   options={model.Options}
   value={this.state.formValue} -> this only the initial render
/>
```

Is there any way I can force the updating of the form value? Or what could be the reason that the value isn't updated?

**Comment by gcanti** [comment]
Hi,

> Or what could be the reason that the value isn't updated?

Maybe https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#rendering-options

> **Warning**. tcomb-form uses `shouldComponentUpdate` aggressively. In order to ensure that tcomb-form detect any change to `type`, `options` or `value` props you have to change references

Make sure you change the reference of `this.state.formValue`

**Comment by jonaswindey** [comment]
Great, that was the issue. Thanks for the info!
