### ISSUE TITLE
Nested object properties reported as invalid even though parent object is optional.

### ISSUE THREAD

**Issue by rudasn** [gcanti/tcomb-form#191]
Note: I'm using tcomb-json-schema to convert a JSON schema to a tcomb object.

Consider an example JSON object describing a `person`.

```
{
  "type": "object",
  "properties": {
    "name": {
      "type": "object",
      "required": [ "first", "last" ],
      "properties": {
        "first": {
          "type": "string"
        },
        "middle": {
          "type": "string"
        },
        "last": {
          "type": "string"
        }
      }
    }
  }
}
```

The `name` property is optional, but it's `first` and `last` properties are required.

**Observed behaviour**
If `first`, `middle`, `last` are all `null`, `name` is reported as 

```
{
  "first": null,
  "middle": null,
  "last": null
}
```

and it's `first` and `last` properties do not pass the validation test (because they are required and null).

**Expected behaviour**
If `first`, `middle`, `last` are all `null`, `name` should pass the validation test (because it's optional).

It is possible to support this kind of behaviour? Where should I start looking into implementing this?

**Comment by gcanti** [comment]
> It is possible to support this kind of behaviour? 

Optional structs are not supported. The simplest workaround I can think of is using a `subtype`:

```js
function isValidName(x) {
  return (!t.Nil.is(x.first) && !t.Nil.is(x.last)) || (t.Nil.is(x.first) && t.Nil.is(x.last) && t.Nil.is(x.middle));
}

const Name = t.subtype(t.struct({
  first: t.maybe(t.String),
  middle: t.maybe(t.String),
  last: t.maybe(t.String)
}), isValidName);

const Foo = t.struct({
  name: Name
}, 'Person');

var options = {
  fields: {
    name: {
      error: 'my error message here'
    }
  }
};
```

**Comment by rudasn** [comment]
Thanks, that looks quite simple. 

Does `tcomb-json-schema` support subtypes and custom validators?

**Comment by gcanti** [comment]
> Does tcomb-json-schema support subtypes and custom validators?

No, AFAIK there's not standard for that, but I can be wrong.

**Comment by VinSpee** [comment]
@gcanti can you explain a little bit _why_ optional `Struct`s aren't supported?

**Comment by gcanti** [comment]
@VinSpee because of a simple reason: till now I didn't come up with a good idea on how to handle them. Let's talk about this topic, I'm quite interested https://github.com/gcanti/tcomb-form/issues/236
