### ISSUE TITLE
Add support of react-v0.14-rc1

### ISSUE THREAD

**Issue by istarkov** [gcanti/tcomb-form#194]
Add support of react-v0.14-rc1

**Comment by gcanti** [comment]
Hi!
Just published v0.7.0 with react-v0.14-rc1 support

Giulio

**Comment by istarkov** [comment]
Super, Thank You!!!!!

**Comment by gcanti** [comment]
Let me know if everything's ok :+1:

**Comment by istarkov** [comment]
All works fine, everything's ok :+1:
Thank you once again!

**Comment by gcanti** [comment]
Great. Thanks for your feedback. Happy hacking
