### ISSUE TITLE
Error on a simple test

### ISSUE THREAD

**Issue by hhumphrey84** [gcanti/tcomb-form#199]
I've created a simple test in my app in an attempt to start using tcomb-form to handle my forms and I'm coming against an error:

Error: Invariant Violation: Form.render()

My code is as below:

```
import React from 'react';
import PlayerActions from '../actions/PlayerActions';
import PlayerStore from '../stores/PlayerStore';
import t from 'tcomb-form';

const Person = t.struct({
  name: t.Str
});

class PlayerAdd extends React.Component {
	
	render() {

		return (
			<form>
				
          <t.form.Form 
            ref='form'
            type={Person} />

				
				<button type='submit' className='btn btn-primary'>Submit</button>
			</form>
		)
	}
}

export default PlayerAdd;
```

Any ideas as to what might be happening / what I've done wrong?

Thanks,
Helen

**Comment by gcanti** [comment]
Just tried your code and it works for me. Could you please post which version of react and tcomb-form you are using and the exact error message?

**Comment by hhumphrey84** [comment]
Thanks for your swift reply, I'm using version 0.13.3 of react and 0.7.1 of
tcomb-form.

**Comment by gcanti** [comment]
Ok then I think the problem could be a double import of the react library: tcomb-form v0.7.1 requires react v0.14.0-rc1 while you are using react 0.13.3. Probably you are importing 2 different copies of react. Try to install tcomb-form v0.6.4 which is compatible with react 0.13.3

**Comment by hhumphrey84** [comment]
Worked a charm. Thank you! I knew it would be simple and now I get to have
fun with your great library. Thanks again

**Comment by gcanti** [comment]
Great. Happy hacking :+1:

**Comment by kiki-le-singe** [comment]
@gcanti Great! It works :) thanks
