### ISSUE TITLE
'required' property

### ISSUE THREAD

**Issue by benmonro** [gcanti/tcomb-form#208]
I want to render a little red * next to required fields.  As far as I can tell the way to check this is like so:

```
        var required = locals.myInput.props.type.name !== 'Maybe';
```

It would be nice to instead just have a cleaner syntax like this:

```
  <div>{locals.myInput.props.type.required && <span>*</span>}</div>
```

**Comment by gcanti** [comment]
A more reliable way would be to test the `meta` object:

```js
var required = ( type.meta.kind !== 'maybe' );
```

**Comment by gcanti** [comment]
Closing in favour of #210
