### ISSUE TITLE
add the type to template locals

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-form#210]

**Comment by benmonro** [comment]
:+1:

**Comment by benmonro** [comment]
@gcanti on a somewhat related note, how do you get the form validation status in the template?  The template is outside of the scope of the react component so I can't access this.refs.form.validate()...

**Comment by gcanti** [comment]
> how do you get the form validation status in the template?

In 

- `locals.error` if not `null` it contains the error message
- `locals.hasError` if `true` the UI should show the error message

**Comment by benmonro** [comment]
is this true in the form layout template as well?  I want to display a summary box rather than just a message next to each element.  I was thinking that in the form layout template I could get to those...

**Comment by gcanti** [comment]
> I want to display a summary box rather than just a message next to each element

mmh it might be tricky... could you please open another issue with a simple example? I'll think about it

**Comment by benmonro** [comment]
sure

**Comment by benmonro** [comment]
#212  @gcanti

**Comment by gcanti** [comment]
Released in v0.6.7 and v0.7.3

**Comment by benmonro** [comment]
@gcanti what is the difference between 0.6 & 0.7?  When I use 0.6.7 it works fine but when I install 0.7.3 I get this error:  `Form.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.`

**Comment by gcanti** [comment]
0.7.x uses react 0.14

**Comment by benmonro** [comment]
ah, ok thanks
