### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by benmonro** [gcanti/tcomb-form#213]
Question.  I have a form with some optional fields.  When the data is submitted, if the optional fields are left blank they have a value of null.  I'm wondering if there's a way to change the default to be empty string or something else...

**Comment by gcanti** [comment]
> I'm wondering if there's a way to change the default to be empty string or something else

Have you tried with a custom transformer? 
Personally I try to keep my forms lean and handle this kind of exceptions at the domain model level.

**Comment by abhishiv** [comment]
Hey gcanti,

I have the same issue and I'm using a transformer as you suggested.

```
	return {
		format: (value) => {
			const ret = value || defaultValue;
			console.log("format", ret);
			return ret;
		},
		parse: (str) => {
		  console.log("parse", str);
			return str;
		}
	};
```

However in my custom factory component, this.props.value is null, while this.state.value is = to defaultValue. I deal with it by having a || clause. But is it by design?

```
    "tcomb": "^2.7.0",
    "tcomb-form": "^0.8.2"
```

**Comment by gcanti** [comment]
> in my custom factory component ... But is it by design?

Yes, you should always read `this.state.value`
