### ISSUE TITLE
Fields are wrapped in a form-group

### ISSUE THREAD

**Issue by kryogenic** [gcanti/tcomb-form#215]
tcomb-form boxes all the input elements in a .form-group causing 15px of un-needed margin between the input and submit button.

Compare the [bootstrap examples](http://getbootstrap.com/css/#forms) to the [tcomb-form playground example](https://gcanti.github.io/resources/tcomb-form/playground/playground.html).

Note: this can be easily solved using the following css:
```
.form-group-depth-0 {
  margin-bottom: 0;
}
```

**Comment by gcanti** [comment]
Hi @kryogenic,
Thanks for pointing out, I'm trying to amend this defect

**Comment by gcanti** [comment]
Released in v0.6.7 and v0.7.3

**Comment by kryogenic** [comment]
thanks!

**Comment by gcanti** [comment]
Let me know if everything's ok ;-)

**Comment by kryogenic** [comment]
working good over here, seems you removed form-group-depth-0 completely
