### ISSUE TITLE
Playground code as example?

### ISSUE THREAD

**Issue by pe3** [gcanti/tcomb-form#216]
Hello. Is the code for [tcomb-form v0.3 playground](http://gcanti.github.io/resources/tcomb-form/playground/playground.html) somewhere? Could it be added under an examples-folder?

**Comment by gcanti** [comment]
Hi,
you can find an old (and no more mantained) copy in https://github.com/gcanti/tcomb-form/releases/tag/v0.3.1
(folder `/docs/playground`)

**Comment by pe3** [comment]
Thanks. I'm researching alternatives for building a form editor. The playground demo is inspiring. I'll have a look.
