### ISSUE TITLE
Buttons in the List component should have type="button"

### ISSUE THREAD

**Issue by leoasis** [gcanti/tcomb-form#218]
Hi!
First of all, awesome library, super flexible and powerful.

Just stumbled upon this "bug". If you wrap your `Form` component inside a `form` (as it is an usual use case, I think), you get the default submit on 'Enter' behavior. The problem is that buttons, by default, have the submit behavior in this case, and the first one will be clicked whenever the user hits enter in any other field.
The buttons generated in the default component and templates in `List`s don't specify the type of the button, and they trigger this default behavior, which I think is not correct. The buttons to add/remove/reorder elements in the list should have the `type="button"` attribute so that this doesn't happen.

In case I'm missing something, or am completely wrong, let me know :P

Thanks again!

**Comment by gcanti** [comment]
Hi @leoasis,

> The buttons to add/remove/reorder elements in the list should have the type="button" attribute so that this doesn't happen

You are right, thanks for pointing out. I'll fix that asap

**Comment by gcanti** [comment]
Released a new version of uvdom-bootstrap https://github.com/gcanti/uvdom-bootstrap/releases/tag/v0.2.4
Re-installing tcomb-form with a fresh dependency should fix this issue.

**Comment by leoasis** [comment]
Wow that was fast, thanks a lot!

**Comment by gcanti** [comment]
Thanks to you @leoasis
