### ISSUE TITLE
Radio component does not have a transformer

### ISSUE THREAD

**Issue by tamagokun** [gcanti/tcomb-form#226]
This only appears to be an issue in IE10 through some cross-browser testing i've been doing.

I can't mount a Radio button field as the Component's `getTransformer` method returns undefined.

I believe adding a transformer to the Radio class would fix this.

**Comment by tamagokun** [comment]
Under further investigation:

It appears that IE10 is unable to see the default transformer that is in Component. Class inheritance must not be working right.

**Comment by tamagokun** [comment]
https://babeljs.io/docs/advanced/caveats/

IE10 does not support `__proto__` that would make sense. I'm not sure if you want to achieve IE10 support or not, feel free to just close this issue out.

**Comment by gcanti** [comment]
Hi!
Thanks for digging into this. From what I understand there are two solutions:

1. adding the default static `transformer` to the `Radio` component
2. using the optional `spec.protoToAssign` babel transformer https://babeljs.io/docs/advanced/transformers/spec/proto-to-assign

I'd go for 1), what do you think?

**Comment by tamagokun** [comment]
I'd prefer 1. It's cleaner that way I think.

**Comment by gcanti** [comment]
Released in v0.6.8 and v0.7.4
