### ISSUE TITLE
optional refinement with custom error message not passing locals.error

### ISSUE THREAD

**Issue by benmonro** [gcanti/tcomb-form#230]
I have a case where my custom error message is not being triggered for a refinement which is wrapped by `maybe`.  Consider the following schema & code:

```
var age = tcb.refinement(tcb.Number, n => n > 17, 'adult');
age.getValidationErrorMessage = function(value, path, context) {
  if(!age.is(value)) {
    return `${value} must be more than 17`;
  }
}
let Person = tcb.struct({
  name: tcb.Str,
  age: tcb.maybe(age),
  ageRequired: age
})

```

When I enter an invalid value for age (say 2 for example).  The required version of age WILL get the error message passed to the template, but the optional one will not.  I verified that the error is present when I call form.validate() but for some reason it's not being passed into the template.  You can see the results here:

![image](https://cloud.githubusercontent.com/assets/399236/10437148/1b71aeaa-70f9-11e5-864c-9efc172bafe5.png)

You'll notice that the optional field is ***NOT*** displaying the error message (because locals.error is undefined for that field), but it ***IS*** displayed for the required version of the same refinement.

**Comment by benmonro** [comment]
JSBin here: (thanks for that JSBin fix :smile: )

http://jsbin.com/maxiti/edit?js,console,output

**Comment by gcanti** [comment]
Thanks @benmonro, working on this...

**Comment by gcanti** [comment]
@benmonro I found a fix. Pushed to master and 0.6.x branches. Could you please give it a try before releasing?

**Comment by benmonro** [comment]
@gcanti you are a legend!  works great, thanks!
