### ISSUE TITLE
Kind is undefined in onChange for nested List

### ISSUE THREAD

**Issue by leoasis** [gcanti/tcomb-form#231]
I have a model that is a `t.struct` that contains a property of `t.list` of `t.struct` which in turn contains a property that is a `t.list`. So basically a list inside a struct inside a list inside a struct :P

Whenever I add or remove an item in the nested list, the `onChange` callback for the form returns with a `kind` of undefined, which is incorrect and should be `add` or `remove` respectively. This works fine with top level lists, but it fails when the list is inside a struct inside another list. I've tracked this to the `onItemChange` function in the `List` component, which doesn't take into account if the change is from a nested list, and completely discards the `kind`.

**Comment by gcanti** [comment]
Hi @leoasis, good catch! Thanks.
Just pushed a fix to master and 0.6.x branches.

**Comment by leoasis** [comment]
@gcanti thanks! I'm really impressed by the speed in which you address all the issues! Thanks a lot again and awesome job

**Comment by gcanti** [comment]
Well, you helped me a lot with your detailed description, thanks again.

**Comment by benmonro** [comment]
@gcanti for president!
