### ISSUE TITLE
rewrite templates with JSX

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-form#260]

**Comment by Xananax** [comment]
I'm working on a proposal for tcomb-form, and I needed the bootstrap templates, so I quickly rewrote them. Maybe you can use this as a base. I tried reimplementing most of the logic that existed in `uvdom-bootstrap` (but haven't yet ported the templates from `tcomb-form`'s boostrap directory)

https://github.com/Xananax/tcomb-bootstrap-templates-temp

There are also additional libraries, for modals and so on. They're written in my own horrendous style (comma first, etc), but I can run a quick regex search-and-replace if you want to use them. Only dependency is [classnames](https://github.com/JedWatson/classnames) (and React, obviously).

**Comment by Xananax** [comment]
Alternatively, you can just tell me what matters to you in terms of coding style (apart from 2 spaces for indents and trailing commas) and I can submit a PR some weeks from now.

**Comment by gcanti** [comment]
Thanks a lot @Xananax, at first sight seem very helpful. I'll take a closer look after the v0.7.7 release (not so far hopefully)
