### ISSUE TITLE
Broilerplate example please?

### ISSUE THREAD

**Issue by tomByrer** [gcanti/tcomb-form#27]
I'm trying to figure out how to use tcom-form, without knowing React.  Could you please provide a simple & clean broilerplate example, or a more detailed listing of how to use?  You list [dependencies](https://github.com/gcanti/tcomb-form#dependencies), but I do not know if those are for the browser or to be compiled developer-side.

**Comment by sm-g** [comment]
No `examples` now?

**Comment by gcanti** [comment]
@sm-g replaced with documentation: https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md

**Comment by sm-g** [comment]
Well, i did found only very simple Working example. Would be nice to see some real app, may be you know good repo for this role?
