### ISSUE TITLE
only a ReactOwner can have refs

### ISSUE THREAD

**Issue by tamagokun** [gcanti/tcomb-form#271]
```
Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded
```

I am upgrading an app to use React 0.14.3, and whenever I try to render a tcomb-form, I get this error thrown. The form appears to render properly, but through my testing it seems only the first form field actually sets its value properly.

The component that is throwing this error is Textbox.

**Comment by tamagokun** [comment]
I still need to confirm that there aren't two reacts getting loaded..

**Comment by gcanti** [comment]
With React 0.14.x you should use tcomb-form 0.7.x

**Comment by tamagokun** [comment]
I'm using 0.7.10. I had a hunch that maybe something didn't update right with npm, and sure enough.. that was the case. I killed node_modules and re-ran npm install and all is well again.

Sorry for the trouble!
