### ISSUE TITLE
Created a module for tcomb-form

### ISSUE THREAD

**Issue by Industrial** [gcanti/tcomb-form#275]
Hi.

I just created a module for tcomb-form called [tcomb-form-types](https://github.com/Industrial/tcomb-form-types) that implements a list of validations/string subtypes. I basically used the `validator` npm module for these functions, and I'm sure I have much to do on it still (any tips/help/pull requests welcome!), but I released a first version on NPM :-)

**Comment by gcanti** [comment]
Great! Thanks for sharing @Industrial

**Comment by saidmoya12** [comment]
Thanks @Industrial; me too, I updated the module tcomb-form-injector for include any component like autocomplete or <input type="range"/> etc...

Sorry for spam

**Comment by Industrial** [comment]
I have not worked on it for a long time, so you can consider it dead (or fork it)
