### ISSUE TITLE
0.8: with default templates, how to arrange two particular fields in one row?

### ISSUE THREAD

**Issue by Firfi** [gcanti/tcomb-form#283]
Hey, I have standard `<Form model={...} options={...}/>`

I have every input on new line as it rendered as `<fieldset>` with `.form-group`-wrapped inputs.

I'd need to add class to two of .form-groups but don't see where to do it; `attrs: {className: }` sets class for only inputs.

Maybe I can extend template somehow? Is there such possibility?

Thanks

**Comment by gcanti** [comment]
> how to arrange two particular fields in one row

Hi, you can use a custom template for your struct:

**Example**

```js
const Type = t.struct({
  name: t.String,
  surname: t.String
})

function template(locals) {
  return (
    <fieldset>
      <div className="col-md-6">
        {locals.inputs.name}
      </div>
      <div className="col-md-6">
        {locals.inputs.surname}
      </div>
    </fieldset>
  )
}

const options = {
  template: template // overrideing the default template just for this struct
}

const App = React.createClass({

  onSubmit(evt) {
    evt.preventDefault()
    const value = this.refs.form.getValue()
    if (value) {
      console.log(value)
    }
  },

  render() {
    return (
      <form onSubmit={this.onSubmit}>
        <t.form.Form
          ref="form"
          type={Type}
          options={options}
        />
        <div className="col-md-12">
          <div className="form-group">
            <button type="submit" className="btn btn-primary">Save</button>
          </div>
        </div>
      </form>
    )
  }

})
```

**Result**

<img width="1139" alt="issue-283" src="https://cloud.githubusercontent.com/assets/878912/12221284/86543800-b794-11e5-9bd3-2a5e1bff1549.png">

**Comment by Firfi** [comment]
thanks @gcanti !
