### ISSUE TITLE
Warning: ScrollView doesn't take rejection well - scrolls anyway

### ISSUE THREAD

**Issue by lrettig** [gcanti/tcomb-form#294]
I get this error continually on a form that lives inside a ScrollView. It appears to be due to this issue: https://github.com/facebook/react-native/issues/1501.

It seems there is at least one proposed solution for `TextInput` inside of a `ScrollView`: cf. https://github.com/facebook/react-native/issues/1501#issuecomment-169099731.

Can this change be made at the tcomb-form level?

Thanks.

**Comment by gcanti** [comment]
Hi @lrettig, please re-open this issue on the [tcomb-form-native](https://github.com/gcanti/tcomb-form-native/issues) repo. This is the web counterpart of tcomb-form.

**Comment by lrettig** [comment]
I figured that out just as you closed this one :) Thanks & sorry

**Comment by gcanti** [comment]
No problem :)
