### ISSUE TITLE
Boolean a Textfield not Checkbox

### ISSUE THREAD

**Issue by ekristen** [gcanti/tcomb-form#295]
I'm using `tcomb-json-schema` with `tcomb-form` and for whatever reason whenever a boolean is converted from `JSON`, the field never renders as a Checkbox, always as Text.

It seems that the bug is right around here, looks like it is comparing functions https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L29

It gets converted during build to something like ... 

```
switch (type.meta.kind) {
      case 'irreducible':
        if (type === _tcombValidation2['default'].Boolean) {
          return Checkbox; // eslint-disable-line no-use-before-define
        } else if (type === _tcombValidation2['default'].Date) {
            return Datetime; // eslint-disable-line no-use-before-define
          }
        return Textbox; // eslint-disable-line no-use-before-define
```

AFAICT `if (type === _tcombValidation2['default'].Boolean) {` will never match

**Comment by gcanti** [comment]
Hi, 

Please could you post your json schema reproducing the issue?

**Comment by ekristen** [comment]
```{
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"email": {
			"type": "string"
		},
		"provider": {
			"type": "array",
			"items": {
				"type": "string",
				"properties": {
					"name": {
						"type": "string"
					}
				}
			}
		},
		"admin": {
			"type": "boolean"
		}
	},
	"required": ["id", "email", "provider"]
}```

**Comment by gcanti** [comment]
Works fine for me

<img width="803" alt="295" src="https://cloud.githubusercontent.com/assets/878912/12851853/720d668a-cc2c-11e5-83c6-3f6ebd93f9fc.png">


Make sure you haven't 2 copies of tcomb in your node_modules

```sh
npm list tcomb
```

**Comment by ekristen** [comment]
```
├─┬ tcomb-form@0.8.1
│ ├─┬ tcomb-form-templates-bootstrap@0.1.2
│ │ └── tcomb@2.6.0
│ └─┬ tcomb-validation@2.3.0
│   └── tcomb@2.6.0
└─┬ tcomb-json-schema@0.2.3
  └── tcomb@2.6.0```

**Comment by ekristen** [comment]
![screen shot 2016-02-05 at 9 20 29 am](https://cloud.githubusercontent.com/assets/48329/12851938/c08b1e3a-cbe9-11e5-94b0-09466274ddb6.png)

**Comment by gcanti** [comment]
Wow, you have **three** copies of `tcomb`. This explains the issue. Seems that somehow npm (version 2 I guess) is not able to catch that `tcomb` is a common dependency. A quick fix would be to list `tcomb` as an explicit dependency in your `package.json`

**Comment by ekristen** [comment]
That did it thanks!. Now my only other problem is that coupled with react, it always marks the admin field as being invalid when I click save.

**Comment by gcanti** [comment]
> it always marks the admin field as being invalid when I click save

Not sure I'm follow, could you please expand a little bit? An image maybe?

**Comment by ekristen** [comment]
When I load the form with default values (like I'm editing a record), if the boolean admin value is "true" the checkbox will be checked. However if I click save, the form validation fails on the `admin` field. If I simply uncheck and recheck, then the validation passes.

**Comment by gcanti** [comment]
Make sure you pass in a boolean (`true` not `"true"`)

Also probably there's a typo in the schema you posted:

```js
"provider": {
  "type": "array",
  "items": {
    "type": "string", // <= this should be object
    "properties": {
      "name": {
        "type": "string"
      }
    }
  }
}
```

**Comment by ekristen** [comment]
Fixed and looks like it is getting passed as "true" not true, I'll have to write a transform for it. Thanks.
