### ISSUE TITLE
Uncaught TypeError: [tcomb] Invalid call to mixin(target, source, [overwrite]): cannot overwrite property "ValidationError" of target object

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb-form#302]
### Version

Tell us which versions you are using:

- tcomb-form v0.8.2
- react v0.14.7

### Expected behaviour

Simply importing the module should not throw this error.

### Actual behaviour

...but it does.

### Steps to reproduce

Simply import the module. That's it.

### Console log (optional)

```
Uncaught TypeError: [tcomb] Invalid call to mixin(target, source, [overwrite]): cannot overwrite property "ValidationError" of target object
```

**Comment by gcanti** [comment]
Hi @volkanunsal,

I can't reproduce this error just importing the package. Could you please provide more details? Maybe the stack trace.
It would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the point where the error is thrown

**Comment by volkanunsal** [comment]
I can't either anymore. Most likely `tcomb-validation` wasn't installed in the first time I tried it because I'd used `npm update` .

**Comment by FranckErnewein** [comment]
I get exactly the same bug,
I remove my node_modules and run a new `npm install`, everything is fine now.

@gcanti unfortunately I didn't inspect the stack trace to tell you more information before :(

**Comment by shide1989** [comment]
Thanks @FranckErnewein, npm i worked for me (with following command) :
`rm -rf node_modules && rm package-lock.json && npm cache clear --force && npm i`
i also relaunched the terminal
