### ISSUE TITLE
Support for Mongoose models?

### ISSUE THREAD

**Issue by ericperez** [gcanti/tcomb-form#307]
Are there any plans (or would it even be within the scope of this project) to support generating forms from [Mongoose](http://mongoosejs.com/) models? That advantage of this is that as a developer you could describe your data model just once and get generated forms via tcom-form 'for free' in addition to being able to store the data in MongoDB using Mongoose. Thanks.

**Comment by gcanti** [comment]
Definitely it's not within the scope of this project, but given a Mongoose schema I guess one could write an adapter, in the same vein of https://github.com/gcanti/tcomb-json-schema

**Comment by ericperez** [comment]
Thanks for for the quick response. Building an adapter for mongoose schemas is an intriguing idea.
