### ISSUE TITLE
Move React to peerDependecies and devDependencies

### ISSUE THREAD

**Issue by maksis** [gcanti/tcomb-form#313]
Having React in dependencies causes confusing errors when people upgrade their projects to use React 15 due to [multiple (conflicting) copies of React being loaded](https://gist.github.com/jimfb/4faa6cbfb1ef476bd105) by the browser. Seems like this project used to have React in peerDepencencies but for some reason that was changed in https://github.com/gcanti/tcomb-form/commit/5834e925f303d603f5c616383656df223c96888e

Related discussion: https://github.com/JedWatson/react-select/issues/88

**Comment by gcanti** [comment]
Hi @maksis,

would it be correct to move react to `peerDependencies` and to add `v15`?

```diff
"dependencies": {
-  "react": "^0.14.0",
  "tcomb-form-templates-bootstrap": "^0.2.0",
  "tcomb-validation": "^3.0.0"
},
+"peerDependencies": {
+  "react": "^0.14.0 || ^15.0.0"
+}
```

**Comment by maksis** [comment]
You'll probably want a dev dependency as well for running the tests

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-form/releases/tag/v0.9.3
