### ISSUE TITLE
Optional or subtyped unions

### ISSUE THREAD

**Issue by lomereiter** [gcanti/tcomb-form#319]
Hi,

I've run into problems while trying to use an optional union. The error happens in `getFormComponent` function: https://github.com/gcanti/tcomb-form/blob/v0.9.3/src/components.js#L58-L62
It seems that either `getType` should go down recursively and replace all unions with actual types, or `getFormComponent` should propagate the value and use `getType` internally (which would necessitate an interface change).

**Comment by gcanti** [comment]
Hi,

actually unions (not only maybe or subtyped unions) are not supported.

**Comment by gcanti** [comment]
Sorry, actually I've forgot this feature, I'll dig into this.

**Comment by gcanti** [comment]
Hi,

I think I got a fix https://github.com/gcanti/tcomb-form/pull/320

**Comment by lomereiter** [comment]
Hi, I checked and it seems to work. Thanks for the quick fix!

**Comment by gcanti** [comment]
Thanks for test this out
