### ISSUE TITLE
Uncaught TypeError: Cannot read property - t.list custom validation and error message

### ISSUE THREAD

**Issue by rajeshps** [gcanti/tcomb-form#322]
### Version

Tell us which versions you are using:

- tcomb-form v0.9.0
- react v0.14.3

Hi,

Suddenly stumbled upon an issue and not sure if its a bug or am doing something odd.

**Scenario:**
Basically trying to have a LIST type and a custom validation to check **duplicate entries** like below

```js
var Invited = t.enums({
  Y: 'Yes',
  N: 'No'
}, 'Invited');

var SpecialType = t.struct({
  specialty: t.String, // <= from options this becomes t.form.Select as factory and select's dropdown values are populated or assigned through state
  invited: Invited
}, 'SpecialType');

function hasDuplicates(a) {
  return _.uniq(a).length !== a.length; 
}

function getIndexedKeysAsArray(x, key) {
  var ret = [];
  for (var i = 0; i < x.length; i++) {
    if (x[i].hasOwnProperty(key)) {
      ret.push(x[i][key]);
    }
  }
  return ret;
}

const CustomListNoDuplicates = t.refinement(t.list(SpecialType), function(x){
    var hasDup = hasDuplicates(getIndexedKeysAsArray(x, "specialty"));
    return !hasDup;
});

CustomListNoDuplicates.getValidationErrorMessage = (value, path, context) => {
  return "Error: Found duplicates";
};

var Type = t.struct({
  specialties: CustomListNoDuplicates,
  affiliation: t.String
});

<Form ref="form" type="{Type}" options={this.state.options} value={this.state.value} onChange={ this.onChange } />

```

All works fine until validation is called with 
`this.refs['form'].validate()`
Properly the validation error is also passed through.
Issue or error happens when again **ADD MORE** is clicked and following error appears in console 

```js
components.js:863 Uncaught TypeError: Cannot read property 
```

**Full trace from console:**
```js
components.js:863 Uncaught TypeError: Cannot read property 
'getValue' of undefinedgetValue @ components.js:863
getError @ components.js:257getLocals @ components.js:293
getLocals @ components.js:991render @ components.js:306
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:587
ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:607
ReactCompositeComponent__renderValidatedComponent @ ReactPerf.js:66
ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:560
ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:544
ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:473
ReactCompositeComponent_updateComponent @ ReactPerf.js:66
ReactCompositeComponentMixin.performUpdateIfNecessary @ ReactCompositeComponent.js:421
ReactReconciler.performUpdateIfNecessary @ ReactReconciler.js:102
runBatchedUpdates @ ReactUpdates.js:129Mixin.perform @ Transaction.js:136
Mixin.perform @ Transaction.js:136assign.perform @ ReactUpdates.js:86
flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66
Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149
ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:94ReactEventListener.dispatchEvent @ ReactEventListener.js:204
```

So, when the ``validate()`` is called the specific function of ``getValue`` is called with length of the given type (LIST) as 2.

![image](https://cloud.githubusercontent.com/assets/4093697/15118478/fac43ed0-1629-11e6-8959-a72b661b6c63.png)

However, when the validation is failed due to duplicate values as mentioned in the refinement, next time the length is 3 without rendering or adding that to the list in actual.

![image](https://cloud.githubusercontent.com/assets/4093697/15118530/2c26225e-162a-11e6-81b2-061ea7464a19.png)

for index 3 which is non exist yet and end up in error:

![image](https://cloud.githubusercontent.com/assets/4093697/15118569/61dd43d2-162a-11e6-8a03-82d1370e78ad.png)

###### Interestingly if below code is commented or removed, everything (add more, remove etc.) works fine without any issues and also the custom validation works too. Only glitch is that am unable to get hold of exact message or reason for validation failure and unable to display appropriate message without the below block.

```js
CustomListNoDuplicates.getValidationErrorMessage = (value, path, context) => {
  return "Error: Found duplicates";
};
```

Please guide on workaround to this specific issue or a better way of achieving of validating duplicate entries in the list and ability to show error message to users.

**Comment by gcanti** [comment]
@rajeshps thanks for the detailed report, working on this...

**Comment by gcanti** [comment]
Got it. If a `getValidationErrorMessage` is defined, `getError` calls `getValue` in order to build the error message, but the new component doesn't yet exist so its index is not contained in `this.refs` and `getValue` throws. I think that a simple check on `this.refs` would fix this issue:

https://github.com/gcanti/tcomb-form/blob/322/src/components.js#L641-L643

**Comment by rajeshps** [comment]
Perfect, checked the fix and works well. Thanks for a quick one.

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-form/releases/tag/v0.9.5
