### ISSUE TITLE
Need a config option to turn off humanize().

### ISSUE THREAD

**Issue by rahimlila** [gcanti/tcomb-form#328]
### Expected behaviour

I want my labels to be rendered as-is and not be modified by the tcomp-form lib..

### Actual behaviour

Your humanize function is messing my labels up . 

```

**Comment by gcanti** [comment]
@rahimlila The `humanize` function is just trying to provide meaningful **defaults**. You can override them https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#label

**Comment by rahimlila** [comment]
I'm using v 0.6.3 but cannot seem to get this working. upgrading to latest
breaks the whole app, so that would be painful.

how can i get this to work with 0.6.3?
