### ISSUE TITLE
Need to have ability to set form attributes as advanced

### ISSUE THREAD

**Issue by rahimlila** [gcanti/tcomb-form#330]
### Version

0.6.3

Tell us which versions you are using:

- tcomb-form 0.6.3

### Expected behaviour

We need the ability to display advanced form attributes differently . Our forms have many inputs and some of them are advanced and not many users will need to change them. In this case, these advanced parameters should be grouped together in a collapsible form group.

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by gcanti** [comment]
You can use a custom template, I guess

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#templates
