### ISSUE TITLE
Broken with jspm

### ISSUE THREAD

**Issue by abhishiv** [gcanti/tcomb-form#331]
Hey gcanti

Right now `lib/main.js` tries to import index.js by using the `./` syntax. That unfortunately doesn't seem to work with jspm according to @jspm/jspm-cli#1580

Can it be changed to `./index.js` so it works with jspm.

- tcomb-form 0.9.5

**Comment by gcanti** [comment]
@abhishiv sure, thanks for pointing out

**Comment by gcanti** [comment]
@abhishiv Released in https://github.com/gcanti/tcomb-form/releases/tag/v0.9.6

**Comment by abhishiv** [comment]
Perfect, works great. Thanks!
