### ISSUE TITLE
Form templates containing tabs do not work

### ISSUE THREAD

**Issue by mandeepbrar** [gcanti/tcomb-form#335]
### Version

Tell us which versions you are using:

- tcomb-form v0.9.7
- react v0.15.0

### Expected behaviour

User should be able to save form when the form elements are split in different tabs

### Actual behaviour
Get an error message 'Invalid value undefined supplied to Struct'.

### Steps to reproduce

1. Provide a template for rendering the form with react-tabs library. (Also tried with react-simpletabs library)
```
<Tabs>
          <TabList>
            <Tab>t1</Tab>
            <Tab>t2</Tab>
          </TabList>
          <TabPanel>
            <div>{locals.inputs.f1}</div>
          </TabPanel>
          <TabPanel>
            <div>{locals.inputs.f2}</div>
          </TabPanel>
        </Tabs>
```
2. Save the form
3. The form fails to save with an error message 'Invalid value undefined supplied to Struct'
4. Remove the tabs from the template. The form works fine.

**Comment by gcanti** [comment]
By default `react-tabs` will only render the selected tab's contents, you can fix that using `forceRenderTabPanel`:

```js
<Tabs forceRenderTabPanel>
...
</Tabs>
```

**Comment by mandeepbrar** [comment]
Thanks. Works great.
