### ISSUE TITLE
Transformers "parse" function never seems to get called?

### ISSUE THREAD

**Issue by awhillas** [gcanti/tcomb-form#336]
### Version

- tcomb-form v0.8.2
- react v0.14.8

### Problem

I have a problem in which the "parse" function never seems to get called. Here is my transformer:
```es6
const tagsTransformer = {

  format: (values) => {  // server representation -> form values
    if(Array.isArray(values)){
      let taxonomys = {};
      values.map((tag) => {
        if (tag.taxonomy in taxonomys)
          taxonomys[tag.taxonomy].push(tag.id);
        else
          taxonomys[tag.taxonomy] = [tag.id];
      });
      return taxonomys;
    }
    else {
      return values;  // it must be idempotent aka ignore junk
    }
  },

  parse: (values) => {  // form values -> server representation
    // array of IDs
    console.log("parse", values);
    return Object.keys(values).reduce((p, c) => p.concat(values[c]), []);
  }
};
```
And here is the console log, note that `parse` never gets called
![screen shot 2016-06-10 at 10 39 28 am](https://cloud.githubusercontent.com/assets/124496/15959231/0994a8f8-2efa-11e6-8789-e1f8ae9ac221.png)
when is `parse` supposed to get called?

**Comment by gcanti** [comment]
> when is parse supposed to get called?

When `getValue` or `validate` is called

**Comment by awhillas** [comment]
But i copy/pasted this from the docs. It ain't happening :(
```es6
  onSubmit() {
    // event.preventDefault(); // not using a submit button
    const value = this.refs.form.getValue();
    if (value) {
      this.props.dispatch(this.submitFormAction()(data));
    } else {
      console.warn(this.refs.form.validate());
    }
  }
```

**Comment by gcanti** [comment]
It's hard to say without the complete code

**Comment by awhillas** [comment]
see above

**Comment by gcanti** [comment]
I've got an error on first rendering, the culprit seems an `undefined` value for `values`, setting a default should fix that:

```js
const tagsTransformer = {

  format: (values = {}) => {  // <= for structs, format should return an object
    ...
  },

  parse: (values) => {
    ...
  }
};
```

**Comment by awhillas** [comment]
I'm not getting an error on first render. Also, the `format` is expecting a list `[]`. taxonomy data looks like [this](http://pastebin.com/anz32B9K) and an object instance from the data base looks like [this](http://pastebin.com/GjZK5ih0).

**Comment by gcanti** [comment]
`format(x: A | B) -> B` is expecting a list (`A`) but returns an object (`B`), so it should accept also an object. If no data is provided on the first rendering, you get an error, hence my suggestion for a default.

Anyway my suggestion is **do not use a transformer** (which runs on every change) in your use case, do the conversion `server representation -> form representation` + `form representation -> server representation` only once and outside `tcomb-form`.

**Comment by awhillas** [comment]
oh, ok, well... what are Transformers for then?

**Comment by gcanti** [comment]
For example when you handle a number contained in a textbox input: you need a way to format the number to a string and a way to parse the string back to a number

**Comment by awhillas** [comment]
Yeah, thats what i'm trying to do! If it (is supposed to) get called when the item is loaded and when it serialises the values of the form on `getValues()` then this is exactly what i need it for. 

Actually, what is the point of doing this on every key stroke? We only care about it when we're submitting. don't we?
