### ISSUE TITLE
Can't change templates

### ISSUE THREAD

**Issue by jadus** [gcanti/tcomb-form#337]
I'm trying to get the semantic template to work and my goal is to write a material-ui template.
But when I install the tcomb-form-templates-semantic npm and write this

```
import React from 'react';
import t from 'tcomb-form/lib';
import i18n from 'tcomb-form/lib/i18n/en';
import semantic from 'tcomb-form-templates-semantic';

t.form.Form.i18n = i18n;
t.form.Form.templates = semantic;
```

I still have the bootstrap markup

**Comment by gcanti** [comment]
Weird, just made a quick test with a fresh install and everything works fine

**Comment by jadus** [comment]
What is really weird is that it seems to work when I import tcomb-form instead of tcomb-form/lib.
Any idea why ?

**Comment by gcanti** [comment]
@jadus Still an issue? Closing this for the moment
