### ISSUE TITLE
Custom Validation for the whole form

### ISSUE THREAD

**Issue by anpr** [gcanti/tcomb-form#339]
Thanks for the excellent library!

### Version

- tcomb-form v0.9.7
- react v0.14.8

### Question

I would like to have a custom validation for my form that allows me to specify that at least one of two attributes must be specified. How can I do this? All I've found is that I can specify custom validation through subtypes, but this doesn't work in this (right?).

Example:
```
const type = t.struct({
    supplier_article_number: t.maybe(t.String),
    gtin: t.maybe(t.String)
)};

// I want to validate that *either* supplier_article_number *or* gtin must be specified.
```

**Comment by gcanti** [comment]
> All I've found is that I can specify custom validation through subtypes

Yep:

```js
const atLeastOne = ({ supplier_article_number, gtin }) => !t.Nil.is(supplier_article_number) || !t.Nil.is(gtin)

const Type = t.refinement(t.struct({
  supplier_article_number: t.maybe(t.String),
  gtin: t.maybe(t.String)
}), atLeastOne)

const options = {
  error: 'At least one!'
}
```

**Comment by anpr** [comment]
Stupid me, thanks for the example!
