### ISSUE TITLE
draftjs support

### ISSUE THREAD

**Issue by treyhoover** [gcanti/tcomb-form#343]
I'm trying to use draftjs as a custom factory/template in a form and don't know whether this is something I should continue to attempt or not. Draftjs models its value as a complex editor state object that needs to be persisted, and the solution I have now is to use t.Any to pass that state back and forth, converting it to plain text only on valid form submissions. 

Is there a way to simplify that so the field sends its plain-text equivalent to the onChange handler while preserving the full state in the editor? And is this so out of line with what tcomb is intended to do that I shouldn't bother?

**Comment by gcanti** [comment]
Hi,  

I don't have any experience with draftjs. How do you convert the editor state to plain text?

**Comment by treyhoover** [comment]
Hey, thanks for writing back. Right now I'm saving the editorState object and converting it like so:

```
editorState.getCurrentContent().getPlainText();
```

I may actually want to preserve more detail about the content though if we decide we want to use it as a rich text editor, which would mean I'd use these functions instead: https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html#converttoraw

**Comment by gcanti** [comment]
Ok, so maybe using a [transformer](https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#transformers), something like this

```js
import t from 'tcomb-form'
import {Editor, EditorState, ContentState} from 'draft-js'

class MyEditor extends React.Component {

  constructor(props) {
    super(props)
    this.state = {
      editorState: props.value ? EditorState.createWithContent(props.value) : EditorState.createEmpty()
    }
    this.onChange = (editorState) => {
      this.setState({editorState})
      this.props.onChange(editorState)
    }
  }

  render() {
    const {editorState} = this.state
    return <Editor editorState={editorState} onChange={this.onChange} />
  }

}

const template = t.form.Form.templates.textbox.clone({
  renderInput: (locals) => {
    return <MyEditor onChange={locals.onChange} value={locals.value} />
  }
})

class MyFactory extends t.form.Component {

  static transformer = { // <= from ?string | EditorState to EditorState
    format: value => {
      if (t.String.is(value)) {
        return ContentState.createFromText(value)
      }
      return value // null, undefined or EditorState
    },
    parse: value => { // <= from EditorState to string
      return value.getCurrentContent().getPlainText()
    }
  }

  getTemplate() {
    return template
  }

}

const Type = t.struct({
  code: t.String
})

const options = {
  fields: {
    code: {
      factory: MyFactory
    }
  }
}

const value = {
  code: 'hello'
}

const App = React.createClass({

  onSubmit(evt) {
    evt.preventDefault()
    const v = this.refs.form.getValue()
    if (v) {
      console.log(v) // eslint-disable-line
    }
  },

  render() {
    return (
      <form onSubmit={this.onSubmit}>
        <t.form.Form
          ref="form"
          type={Type}
          options={options}
          value={value}
        />
        <div className="form-group">
          <button type="submit" className="btn btn-primary">Save</button>
        </div>
      </form>
    )
  }

})
```

**Comment by treyhoover** [comment]
Thanks again for the quick reply. I did try something similar, but that was causing issues with cursor position and other metadata being lost as the editor state was constantly recreated from text. Unfortunately I don't think there's a good way to make the two work together.
