### ISSUE TITLE
How can I create a Bootstrap inline form

### ISSUE THREAD

**Issue by msaron** [gcanti/tcomb-form#348]
I am using tcomb-form v0.9.8 and react v15.2.1

How can I create a Bootstrap inline form? Currently I use the following CSS to display the form exactly as I want.

        .form-inline .form-control {
            display: block;
        }

What the above CSS does is create labels on top and the controls on the bottom but the form-control itself flows inline. Form class is form-line. 

Thanks.

**Comment by gcanti** [comment]
Not sure I'm following, exactly what's the issue here?

**Comment by msaron** [comment]
I want to display the form like the Bootstrap form class 'form-inline'. That displays the labels and controls inline.  See http://getbootstrap.com/css/#forms-inline

**Comment by gcanti** [comment]
I mean, inline forms are not officially supported, but setting the `form-inline` class on your container `<form>` doesn't work?

**Comment by msaron** [comment]
Figured it out after trying various settings. I set the container div style to display: 'inline'. Then I set the following:

        .form-control {
            display: block;
        }

        .form-group {
            display: inline-block;
        }

        .fieldset {
            display: inline;
        }

And now it works fine. 

Thanks.
