### ISSUE TITLE
validate() doesn't set hasError to true even when there are errors

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb-form#350]
### Version

- tcomb-form v0.9.9

### Expected behaviour

Given the following form:

```js

class Page extends React.Component {
  onSubmit(e) {
    e.preventDefault()
    this.refs.form.validate()
  }
  return <form onSubmit={::this.onSubmit}>
    <t.Form ref='form' type={t.struct({name: t.String})} />
   <button type='submit'>Submit</button>
  </form>
}
```

I would expect to see an error message when I click the submit button.

### Actual behaviour

There is no error message.

I read the source code carefully. [This is the line](https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L521) that is causing the problem. As you can see, `hasError` is never updated if the errors array has a non-zero number of values. I don't think this is intentional.

I would suggest changing that to read

```js
this.setState({ hasError: errors.length > 0 });
```

Or maybe update the value in an `else` clause above that line.

**Comment by gcanti** [comment]
Thanks @volkanunsal !
Released a fix in https://github.com/gcanti/tcomb-form/releases/tag/v0.9.10
