### ISSUE TITLE
Maybe 'both' should be another possible value for 'auto'

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb-form#353]
It would be very useful for me if there was another value for the `auto` option called 'both'. I often need to have both labels and placeholders on a form. 

I can submit a pull request for this feature, if it seems interesting to you, @gcanti .

**Comment by gcanti** [comment]
> I can submit a pull request for this feature

Ok. But, out of curiosity, do you need both labels and placeholders even if they will be equal?

**Comment by volkanunsal** [comment]
@gcanti You may be right. My use case is probably an edge case. Most of the time one or the other works just fine. I don't want to introduce additional complexity for a feature that may not be all that meaningful for most people using the library.
