### ISSUE TITLE
validate as you type?

### ISSUE THREAD

**Issue by matthewmueller** [gcanti/tcomb-form#366]
I feel like this is possible, but I haven't figured it out yet. Basically as you type, check against the domain to see if it's valid?

Given this domain

```js
var user = t.struct({
  firstName: t.String,
  lastName: t.String
}
```

Is it possible to validate just `firstName`?

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#accessing-fields

**Comment by matthewmueller** [comment]
ah there it is – thanks!
