### ISSUE TITLE
Custom Inputs

### ISSUE THREAD

**Issue by srconklin** [gcanti/tcomb-form#37]
I  really want to use this really nice filterable multiselect box in a project (the Add and Remove example) in the demo here
http://insin.github.io/react-filtered-multiselect/

Would I be able to integrate this kind of a component into tcomb-form using the instructions here
http://gcanti.github.io/tcomb-form/guide/index.html#custom-inputs

or would this not quite work as i hope? 

Thanks for any advice.

**Comment by snario** [comment]
Hi @gcanti, I'm having trouble getting this setup to work. The example above doesn't seem to work for me on 0.4.4. Would you be able to provide a complete example that I can work off of? Thanks.

**Comment by saidmoya12** [comment]
Could use my library tcomb-form-injector
Sorry for spam
