### ISSUE TITLE
Provide a method of getting value of invalid form

### ISSUE THREAD

**Issue by thugcee** [gcanti/tcomb-form#370]
### Version

Tell us which versions you are using:

- tcomb-form v0.9.10
- react v15.4.1

### Expected behaviour

Since there is Form.validate(), Form.getValue() should return a value without validation or provide a separate method to get a form value without validation.

This is required for all kinds of programmatic form filling based on user's selections in the form. For example, in some order form, one would like to copy customer's address to shipping address. 

### Actual behaviour

Form.getValue() returns null for invalid forms, thus forcing developer to read all fields values one by one using form.getComponent(path) to recreate form's state.

Or maybe there is already some other way to do this?

### Steps to reproduce

1. create a form with required fields
2. allow user to fill some fields and click a button
3. in the button's onClick handler, try to programmatically fill the rest of the fields

**Comment by bpicolo** [comment]
It's digging into not-really-public interfaces, but:
this.refs.form.refs.input.getValue()

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#validate

**Comment by thugcee** [comment]
> https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#validate

`form.validate().value` works.
Thank you.
