### ISSUE TITLE
0.9.12 release break default List behaviuor

### ISSUE THREAD

**Issue by gbiryukov** [gcanti/tcomb-form#379]
### Version
- tcomb-form v0.9.12
- react v0.15.4

### Expected behaviour
Default value of new list items should be `undefined`

### Actual behaviour
Default value of new items is instance of `SyntheticMouseEvent`. It cause weird validation errors messages on new list items

### Steps to reproduce

1. Create custom list template and use it with default `List` factory
2. Pass add click handler from locals to any button as prop i.e. `<button type="button" onClick={locals.add.click} />`
3. Press this button and you will receive `SyntheticMouseEvent` as new item in list

**Comment by karlguillotte** [comment]
Yeah! Right. Did not get that problem as I was calling that function myself from my template. Sorry about that. Perhaps you could revert my change and I will just extend the list component myself.

**Comment by gcanti** [comment]
> Perhaps you could revert my change and I will just extend the list component myself

Ok, thanks @karlguillotte

**Comment by gcanti** [comment]
Reverted in https://github.com/gcanti/tcomb-form/releases/tag/v0.9.13
