### ISSUE TITLE
The t form does not style with the bootstrap styles.

### ISSUE THREAD

**Issue by elimau** [gcanti/tcomb-form#384]
### Version
- tcomb-form v0.9.16
- react v5.5.4

### Expected behaviour
When I create a t form react component, it should have the bootstrap styling.
e.g. the button should have the primary colours etc.

### Actual behaviour

none of the styling comes through.

### Steps to reproduce

1. Here is my App.js
```
import React, { Component } from 'react';
import t from 'tcomb-form';

const Form = t.form.Form;

// define your domain model with tcomb
// https://github.com/gcanti/tcomb
const Person = t.struct({
  name: t.String,
  surname: t.String
});

class App extends Component {

  save() {
    // call getValue() to get the values of the form
    var value = this.refs.form.getValue();
    // if validation fails, value will be null
    if (value) {
      // value here is an instance of Person
      console.log(value);
    }
  }

  render() {
    return (
      <div>
        <Form
          ref="form"
          type={Person}
        />
        <button onClick={this.save}>Save</button>
        <div className="form-group" onClick={this.save}>
          <button type="submit" className="btn btn-primary">Send</button>
        </div>
      </div>
    );
  }
}

export default App;
```

**Comment by gcanti** [comment]
The UI is completely unstyled? Did you include the bootstrap css in your page?

**Comment by elimau** [comment]
Thanks. I added the css to my app and it worked. Sorry, i didnt know that. Is that in the documentation? Do I need to also include the bootstrap js? 
I added bootstrap 3 css. You are using bootstrap 3 right? Any plans to move to bootstrap 4 or other any other theme/ui kit?
Thanks alot.

**Comment by gcanti** [comment]
> Do I need to also include the bootstrap js?

No, only the css is required

> Any plans to move to bootstrap 4 or other any other theme/ui kit?

There are semantic ui templates https://github.com/gcanti/tcomb-form-templates-semantic. 

Adding a theme means to write a bunch of templates, the engine (this library) should stay the same
