### ISSUE TITLE
can any body say me how to run this code and where can i see output????

### ISSUE THREAD

**Issue by Zalasanjay** [gcanti/tcomb-form#391]
### Version

Tell us which versions you are using:

- tcomb-form v0.8.?
- react v0.14.?

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by gcanti** [comment]
Your question is too generic. In the future, consider asking questions like this in StackOverflow, thanks.
