### ISSUE TITLE
Create large text field to enter 300 chars or more. 

### ISSUE THREAD

**Issue by Herxheimer** [gcanti/tcomb-form#393]
I'm trying to create a customer support form that lets a user describe the issues they are having. I'm not sure how to create a large text field in tcomb 

[
![example-large-text-field](https://user-images.githubusercontent.com/25973054/27996618-2b25af8a-64b4-11e7-9a2a-f76ce31fc93d.png)
](url)

**Comment by gcanti** [comment]
type attribute = `textarea`, see https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#textbox-options

**Comment by Herxheimer** [comment]
I tried setting the type attribute but nothing happened 

Code: 
      
    const tcombForm = t.struct({
      test: t.String
        });

    const options = {
     fields: {
       test: {
         type: 'textarea'
        },
      }
    };

**Comment by gcanti** [comment]
Just tried with

```js
const tcombForm = t.struct({
  test: t.String
})

const options = {
  fields: {
    test: {
      type: 'textarea',
      attrs: {
        rows: 20
      }
    }
  }
}
```

and works fine

**Comment by Herxheimer** [comment]
Thanks, but I tried your code in Atom and in a tcomb virtual playground here https://gcanti.github.io/resources/tcomb-form/playground/playground.html ...yet it still didn't work. 

Do you have a link to a working example that I could look at?

**Comment by gcanti** [comment]
Beware the playground is outdated

**Comment by Herxheimer** [comment]
O ok that makes sense, I still tried the code in a hot loaded RN project but it didn't work. Is there a code example I could look at?

**Comment by gcanti** [comment]
Wait, RN means React Native? Not sure if tcomb-form is able to run there..

**Comment by Herxheimer** [comment]
Yes React Native, I've been using tcomb forms for my project and so far everything else has worked (forms, validation, styling) except for the text area

**Comment by gcanti** [comment]
I'm not by any means a mobile developer so maybe in the meanwhile something has changed, but I thought you have to use `tcomb-form-native` with RN

**Comment by Herxheimer** [comment]
O no you're correct, I guess I posted this in the wrong thread. 

Thanks!
