### ISSUE TITLE
Nested list factory

### ISSUE THREAD

**Issue by DKunin** [gcanti/tcomb-form#42]
Hi there! Thanks for the awesome form library - works like a charm and very well structrured!

Small question - can I use a custom factory - on only one field in the t.list? So I can maintaint the add/remove functionality?

The thing is - I need to create a list with date type input - but I have to support IE8 - so I have a custom date input widget.

Thanks in advance!

**Comment by gcanti** [comment]
Hi!

> The thing is - I need to create a list with date type input - but I have to support IE8 - so I have a custom date input widget.

It shouldn't be a problem.
Could you write down the type you'll call `t.form.create` with?
Is it something like this?

```js
var MyList = t.list(t.Dat);
```

or is it more complex? Also, is your custom widget closed source? Otherwise I can try to put up a little example for you
(integrating a backward compatible date picker was in my todo list #5)

**Comment by DKunin** [comment]
The list is a bit more complex - it should be a list of person experience - so it should have two dates and a string, so more something like this:


     var Position = t.struct({
        date_start: t.maybe(t.Str),
        date_finish: t.maybe(t.Str),
        job_descr: t.maybe(t.Str)
      });
    var PositionList = t.list(Position);

I tried to set factory like this, but it didn't work, I did manage to set a custom factory for the whole list - but lost the add/remove functionality:

      var FormTest = t.form.create(CV,{
          fields: {
            positions: {
               date_start: custom_factory
            }
          }
          }
      });

The code to datepicker was found on the web - I, actually forgot where - because I didn't use the original repo - but forked it and made some changes, now it looks like this:
https://gist.github.com/DKunin/77d7261a39e12b9a6a09

**Comment by gcanti** [comment]
Hi,
writing a custom factory is quite expensive, I think the easiest solution is to write a custom template:

http://gcanti.github.io/tcomb-form/guide/index.html#templates

This is my working example:

```js
'use strict';

var React = require('react/addons');
var t = require('tcomb-form');
var DatePickerInput = require('./DatePickerInput.jsx');

var Position = t.struct({
  // here maybe is used but it seems your widget requires always a date
  date_start: t.maybe(t.Dat), 
  date_finish: t.maybe(t.Dat),
  job_descr: t.maybe(t.Str)
});

var PositionList = t.list(Position);

//
// * custom template definition *
//
function datePickerTemplate(locals) {

  var date = !t.Nil.is(locals.value) ? new Date(parseInt(locals.value)) : new Date();

  function onChangeDate(date) {
    locals.onChange(date)
  }

  // here you can customize the rendering
  // at the moment I just added a bootstrap form-group wrapper as example
  // see http://gcanti.github.io/tcomb-form/guide/index.html#templates
  // as a reference implementation for placeholder, label, error message etc...
  return (
    <div className="form-group">
      <DatePickerInput date={date} onChangeDate={onChangeDate} />
    </div>
  );
}

//
// * custom transformer definition *
//
// datePickerTransformer will be redundant in v0.3-rc3
// once https://github.com/gcanti/tcomb-form/issues/43 will land on master
// at the moment is required
var datePickerTransformer = {
  // serialize from date to string
  format: function (date) {
    return date ? date.getTime() + '' : null;
  },
  parse: function (value) {
    return value;
  }
};

var Form = t.form.create(PositionList, {
  // item option: see http://gcanti.github.io/tcomb-form/guide/index.html#list-item
  item: {
    fields: {
      date_start: {
        template: datePickerTemplate,
        transformer: datePickerTransformer
      },
      date_finish: {
        template: datePickerTemplate,
        transformer: datePickerTransformer
      }
    }
  }
});

var App = React.createClass({

  onClick: function () {
    var value = this.refs.form.getValue();
    // getValue returns null if validation failed
    if (value) {
      console.log(value);
    }
  },

  render: function () {
    return (
      <div>
        <Form ref="form" />
        <button onClick={this.onClick}>Click me</button>
      </div>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Note**

In my project I made a change at line 207 of DatePickerInput.jsx:

from

```js
value={this.props.dateFormatter(this.props.date)}
```

to 

```js
value={this.props.dateFormatter(this.state.date)}
```

otherwise the readonly textbox doesn't change its value when selecting a date (or I goofed with the widget?)

**Comment by DKunin** [comment]
It's ok - I think I put props there because I was constantly changing the parent - but - it should work fine I guess!

Thanks for very detailed solution! It works wonderful, but what if I need to have another fields in the same form - is it possible - or should I always use seperate form for such constructs?

**Comment by gcanti** [comment]
> what if I need to have another fields in the same form is it possible...

Sure. You can add any field you want just nesting `opts`. Here an example with an additional `name` field:

```js
var Position = t.struct({
  date_start: t.maybe(t.Dat),
  date_finish: t.maybe(t.Dat),
  job_descr: t.maybe(t.Str)
});

// this is the main form
var Person = t.struct({
  name: t.Str,
  positions: t.list(Position) // list of positions
});

function datePickerTemplate(locals) {
...
};

var datePickerTransformer = {
...
};

var Form = t.form.create(Person, {
  fields: {
    positions: {
      item: {
        fields: {
          date_start: {
            template: datePickerTemplate,
            transformer: datePickerTransformer
          },
          date_finish: {
            template: datePickerTemplate,
            transformer: datePickerTransformer
          }
        }
      }
    }
  }
});
```

**Comment by DKunin** [comment]
Sweet, thanks so much! You practicaly saved me lots of headache!

There is another question thats bugging me - I'm not sure if I should open new issue - or just ask here - I'm guessing the question is somewhat similiar. 

I know I can make a field optional based on another field, checkbox for example - but can I make a field visible or hidden based on the checkbox, not on validation - but on the change of checkbox? I'm guessing that is also has to do with templates - but I'm not sure how I should go about it. Sorry for being such a bother)

**Comment by gcanti** [comment]
> There is another question thats bugging me - I'm not sure if I should **open new issue**

Yes please, so that it can be helpful for other users as well!

**Comment by DKunin** [comment]
Ok, thanks!
