### ISSUE TITLE
onFocus event handler

### ISSUE THREAD

**Issue by srconklin** [gcanti/tcomb-form#46]
I read the docs but did not immediately see how i would add an onFocus handler to one of my fields in a tcomb-form. 
Is this possible?

**Comment by srconklin** [comment]
..and  i would like to be able to set the Bootsrap attribute ->  autoFocus on one of my textboxes.

**Comment by gcanti** [comment]
> I read the docs but did not immediately see how i would add an onFocus handler to one of my fields in a tcomb-form. 
Is this possible?

At the moment no. The workaround could be to use `componentDidMount` and `refs`:

```js
var Person = t.struct({
  name: t.Str, // two string properties
  surname: t.Str
});

var Form = t.form.create(Person);

var App = React.createClass({

  componentDidMount: function () {
    var node = this.refs.form.refs.input.refs.name.getDOMNode();
    // set focus workaround
    node.children[1].focus();
    // add autofocus attribute workaround
    node.children[1].setAttribute('autofocus', true);
  },

  onClick: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render: function () {
    return (
      <div>
        <Form ref="form" />
        <button onClick={this.onClick}>Click me</button>
      </div>
    );
  }

});
```

> ..and i would like to be able to set the Bootstrap attribute 'autoFocus' on one of my textboxes.

AFAIK `autofocus` is not a Bootstrap thing but HTML5. I'll add an issue for the next release, thanks!

**Comment by srconklin** [comment]
NIce.. thank you... that works great... 
sorry, i did mean HTML5

**Comment by gcanti** [comment]
Great. Thanks for the feature suggestion.
