### ISSUE TITLE
add autofocus attribute support

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-form#47]

**Comment by srconklin** [comment]
I can seem to get autoFocus to work... 
is this not they way to specify it? 

 var LoginForm = t.struct({
            email: aValidEmail
   });

 var Form = t.form.create(LoginForm, {
                     email : {
                    autoFocus: true
                    
                }
            }

**Comment by gcanti** [comment]
It's correct, but the autoFocus feature is only on master. I'll release the v0.3 in a couple of days
when the tuple support will be complete (or you can link the master branch in the meanwhile).

**Comment by srconklin** [comment]
ah! i was just noticing that installing from NPM did not have those changes.. will wait for v0.3. thanks.

**Comment by gcanti** [comment]
v0.3.0 released. I decided to release with tuples as an experimental feature to speed up the release cycle. Let me know if it's everything ok with autoFocus.

**Comment by srconklin** [comment]
Thanks. I will give this a try later today...

**Comment by srconklin** [comment]
it is not working for me... I don't see my form element having the focus on initial load
I wonder if it related to this which i have also experienced.
https://github.com/gcanti/tcomb-form/issues/51

**Comment by chasm** [comment]
Autofocus still does not seem to work. Am I missing something or is this still broken?

**Comment by gcanti** [comment]
Hi,
starting from v0.5 autoFocus is moved in the `attrs` option:

```js
var Person = t.struct({
  name: t.Str,
  surname: t.Str
});

var options = {
  fields: {
    name: {
      attrs: {
        autoFocus: true
      }
    }
  }
};
```

**Comment by chasm** [comment]
Brilliant! Works perfectly, and a nice improvement. Thanks!
