### ISSUE TITLE
Discussion: Load "Values" from external source

### ISSUE THREAD

**Issue by timarney** [gcanti/tcomb-form#48]
I see I can pass in default values via
Form ref="form" value={value}
<Form ref="form" value={data} /> or var Form = t.form.create(Person, {value: value});

What's the recommended way to load form values/data from an external source (i.e. editing a previously submitted form).  

I did it by updating my data values and than forceUpdate() to re-render but is there a better way?

**Comment by gcanti** [comment]
Hi!

let me understand the data flow:

1. you load the default values for the first time and pass in then via `<Form ref="form" value={value} />` or `var Form = t.form.create(Person, {value: value})` (it's the same)
2. you retrieve the current values via `var value = getValue()` (`value` and the form values are in sync)
3. ???

**Comment by timarney** [comment]
Say I get my form values via an ajax call - 

One way - which would work the way I see your example:
1 - load page -> make ajax request (delay) -> get data ->  Form = t.form.create(Person, {value: value}); + Render Form
====================================
I'm new to React but this seems to be the preferred React way from my understanding. 

Load Values into form on componentDidMount.

2 - Load Page -> Render Form (no values) -> Load Values into form on componentDidMount
i.e. like sample here
http://facebook.github.io/react/tips/initial-ajax.html

I can currently render the form on page load and than re-render when I get the data.

========================================

**Comment by gcanti** [comment]
Ah ok. I tend to inject the data as a `prop` avoiding to rely on lifecycle methods such `componentDidMount`. But I'd say it's really a matter of taste.
I don't like to write business logic into components and in my opinion knowing how to retrieve the proper data is a fundamental aspect of app logic. Maybe the only palatable case is if that component is a top level component.

Besides, injecting data from outside in general helps the reuse of code (think of server side rendering).

**Comment by timarney** [comment]
Okay - makes sense thanks for the insights.
