### ISSUE TITLE
default values from props

### ISSUE THREAD

**Issue by srconklin** [gcanti/tcomb-form#49]
How would i go about using a tcombs-form as an edit form that loads the values of the form elements which are to be pushed into the component via props which will be triggered say by the onChange of a select box in another component... 
 I am already doing this in a mockup that i am working on but want to to turn the form at right into a t-combs form so i get data validation..  see screenshot

https://www.evernote.com/shard/s349/sh/6ce9855a-f3dc-4fb2-85fe-abf7d94201e9/567614f3336842347fa9217546525fbd

i guess i would need to create the form all over again in the render method passing in the values object every time the component receives new props?  or can i just reset the values when they change? 
or do you have a better idea?

**Comment by gcanti** [comment]
Have you tried to add the `value` prop to the form?

http://gcanti.github.io/tcomb-form/guide/index.html#fieldset-value

In your case:

```js
var RedComponent = React.createClass({
  render: function() {
    return (
      <form>
        <Form value={{agency: this.props.agency}} />
      </form>
    );
  }
});
```

**Comment by srconklin** [comment]
I missed that in the docs.. that worked beautifully.  Thank You!
