### ISSUE TITLE
Enums with numbers

### ISSUE THREAD

**Issue by RileyTomasek** [gcanti/tcomb-form#50]
Is it possible to use an enum with numbers as the keys? My dates are currently stored as:
```
{
  month: 01,
  year: 2015
}
```
and I would like to be able to do:
```
var Months = t.enums({ 1: 'January', 2: 'February', ... });
var Years = t.enums({ 2015: '2015', 2014: '2014' });
var Date = t.struct({ month: Months, year: Years });
```
The only solution I could come up with currently is to transform the numbers to string when receiving them from the server and then back to numbers before sending them back. Not idea.

Thanks!

**Comment by gcanti** [comment]
> Is it possible to use an enum with numbers as the keys

The current implementation uses a hash to store the enums, since in JavaScript
hash keys are strings (or automatically converted to strings) I'd say no.

If you don't strictly need an enum, you could define `Month` and `Year` as subtypes, e.g.

```js
// I'll define `Integer` to show you a "composable approach"
// but feel free to define just 2 predicates for Month and Year...

var Integer = t.subtype(t.Num, function (n) {
  return n % 1 === 0;
});

var Month = t.subtype(Integer, function (n) {
  return n >= 1 && n <= 12;
});

var Year = t.subtype(Integer, function (n) {
  return n >= 2014 && n <= 2015;
});
```

**Comment by RileyTomasek** [comment]
Thanks @gcanti. I think that is a much cleaner way to setup the model, but is there an easy way to get that to display as a select element containing all possible values?

**Comment by gcanti** [comment]
Oh sorry, this is the tcomb-form lib not tcomb :). Obviously you want to show months and years as a select! In that case I'm afraid there is not clean solution besides what you're already doing.

**Comment by RileyTomasek** [comment]
Could I use a transformer? Also, on an unrelated note, what is the best way to get to JSON from form.getValue()?

**Comment by gcanti** [comment]
> Could I use a transformer

Unfortunately transformers are only for textboxes at the moment, otherwise you could do something like this:

```js
var Month = t.subtype(Integer, function (n) {
  return n % 1 === 0 && n >= 1 && n <= 12;
});

var DisplayMonth = t.enums({ 1: 'January', 2: 'February' });
// build options by hand
DisplayMonth.options = Object.keys(DisplayMonth.meta.map).map(function (value) {
  return {value: value, text: DisplayMonth.meta.map[value]};
});

var Person = t.struct({
  month: Month
});

var Form = t.form.create(Person, {
  fields: {
    month: {
      // override factory
      factory: t.form.select,
      // custom options
      options: DisplayMonth.options,
      // number <-> string
      transformer: {
        function format(v) { return String(v); }
        function parse(v) { return parseInt(v, 10); }
      }
    }
  }
});
```

But it's super verbose. At this point it's better to write a reusable custom template or a custom factory.

> what is the best way to get to JSON from form.getValue()

I'm afraid I don't understand: `form.getValue()` gives you an instance of your model. Now if your model is only composed by JSON compatible types (null, string, number, boolean), you already have a JSON.
