### ISSUE TITLE
add all bootstrap goodies

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-form#6]
- Add-ons
- horizontal forms
- inline forms
- inline inputs
- disabled inputs
- readOnly inputs
- control sizing
- column sizing

**Comment by karlguillotte** [comment]
Hi @gcanti ! 

First of all. Thanks for creating and maintaining this library. 

Do you have plans to add the static control component as well? It would be a nice complement to the library. 

http://getbootstrap.com/css/#forms-controls-static

Grazie mille!

**Comment by gcanti** [comment]
Hi!

> I added it to my project, but just thought it would great to add it as a factory in the library.

Sure. Do you mind to send a PR? It would be great
