### ISSUE TITLE
Always show placeholders that are set

### ISSUE THREAD

**Issue by KyleAMathews** [gcanti/tcomb-form#61]
I want labels but I also want placeholders for demo content. Right now if labels are set then my manually set placeholders are ignored. This line is the problem https://github.com/gcanti/tcomb-form/blob/04ad3fd9a2bb247e271d5067adc512f2471602ba/lib/components/Textbox.js#L62

**Comment by KyleAMathews** [comment]
Can make a pull request but not confident yet enough in my understanding of tcomb's internals to guess what you'd want. I'd suggest just adding a `if (opts.placeholder) { placeholder = opts.placeholder; }` line.

**Comment by gcanti** [comment]
> I also want placeholders for demo content

Oh, never thought to this use case. Nice one. I guess this could be the algorithm:

```js
// default to null
var placeholder = null;

// ingnore the placeholder if auto === 'none'
if (ctx.auto !== 'none') {

  // use the option value (if is manually set)
  placeholder = opts.placeholder;

  // fallback only if there is not a label
  if (!placeholder && !label) {
    placeholder = ctx.getDefaultLabel();
  }

}
```

I'll do some tests (and write more comments in the code).

**Comment by KyleAMathews** [comment]
Shouldn't a manually set placeholder *always* be shown?

**Comment by gcanti** [comment]
Yes, you are right (sorry, slept only 4 hours, damn reactjsconf :)

```js
// always use the option value if is manually set
var placeholder = opts.placeholder;
if (!label && !placeholder && ctx.auto === 'placeholders') {
  // add automatically a placeholder only if there is not a label (manually or automatically set),
  // nor a placeholder manually set AND the 'placeholders' auto option is turned on
  placeholder = ctx.getDefaultLabel();
}
```

Same thing for labels I guess.
