### ISSUE TITLE
"auto" not great name for option for selecting label/placeholder strategy

### ISSUE THREAD

**Issue by KyleAMathews** [gcanti/tcomb-form#62]

**Comment by gcanti** [comment]
I agree, any suggestions?

**Comment by KyleAMathews** [comment]
I'd actually suggest to defaulting to labels and not placeholder and perhaps just not support auto-placeholders at all. UX research comes pretty firmly against using placeholders instead of labels ([1](http://www.pardot.com/faqs/forms/placeholders-and-labels/) [2](http://www.nngroup.com/articles/form-design-placeholders/) [3](http://baymard.com/blog/mobile-forms-avoid-inline-labels)).

I'd suggest the option just be `autoLabel` which defaults to true but can be overridden if you pass in a field option for label. If people want placeholders (useful for examples like what I'm doing in my app) then they can set them explicitly.

Thoughts?

**Comment by gcanti** [comment]
> I'd actually suggest to defaulting to labels and not placeholder

I agree.

> just not support auto-placeholders at all

Not sure, although it's true what you say about UX research, there are plenty of forms out there (especially on mobile) using placeholders. Anyway once the `auto` option is defaulted to 'labels' and #61 is fixed, I'd say it's not much of a problem having a `placeholders` value for `auto`

**Comment by KyleAMathews** [comment]
Yeah, auto placeholders isn't the worst thing in the world.

**Comment by KyleAMathews** [comment]
Another way of handling this option I'll throw out there:

```javascript
autoLabel: true // the default
autoLabel: false // no automatically generated anything
autoLabel: 'placeholder'
```

This feels pretty clean and clear. It's much more obvious what `autoLabel` means and I like `false` more than `'none'`.

**Comment by gcanti** [comment]
Sure. The fact is that using an enum for `auto` is handy for type checks.

Example: 

- go to http://gcanti.github.io/tcomb-form/playground/index.html (playground v0.3 but it's the same for v0.4)
- select the "9. Automatically generated labels" example
- try to change the "labels" value in "label"

the error to the right is nice and descriptive (and easy to implement)

actually, all the options are type checked!

**Comment by KyleAMathews** [comment]
True — that is nicer than true/false.
