### ISSUE TITLE
disableRemove on list is ignored?

### ISSUE THREAD

**Issue by colemanserious** [gcanti/tcomb-form#65]
Using 0.3.0-rc2, and then tested again in the tcomb-form v0.4 playground, disableRemove appears to have no effect for lists, either when put in as an option overall, or on a field level.  

Example used in v0.4 playground:

```
// use t.list to define a list
var type = t.list(t.Str);
	
var options = {
	disableRemove: true,
  //disableAdd: true,
  disableOrder: true // try to decomment this line to disable re-arranging
};
```

**Comment by gcanti** [comment]
typo here:

https://github.com/gcanti/tcomb-form/blob/master/lib/components/List.js#L148

`disabledRemove` instead of `disableRemove`

Thanks!

**Comment by colemanserious** [comment]
Actually, tested that, as well, after checking the source.  No dice.  

Local futzing suggests that disabledRemove will work, if api.List is also updated to show disabledRemove.   Preferred fix is to fix List.js, or api?

**Comment by gcanti** [comment]
I'd say List.js
