### ISSUE TITLE
How should one attach event handlers to specific fields?

### ISSUE THREAD

**Issue by andrest** [gcanti/tcomb-form#67]
I have a User form that has:
- password
- email

I'd like to check if the email is taken when onBlur fires on the password field. According to the docs, the Form itself only takes onChange handler.

Do I have to write a custom template, or is there an easier solution?

**Comment by gcanti** [comment]
> write a custom template

Hi, yes at the moment there is no easier solution (#53)

**Comment by andrest** [comment]
Hi,

When one is using a template (Bootstrap, Gridforms, etc.) that would mean duplicating a lot of code. E.g. dealing with errors, labels, value getters, etc. Not ideal.
