### ISSUE TITLE
A template for a sub-type

### ISSUE THREAD

**Issue by andrest** [gcanti/tcomb-form#68]
What I have is a simple credit card form.
```javascript
    var CreditCard = t.subtype(t.Num, function (n) {
      // sub-type
    });

    var creditcard = t.struct({
      number: CreditCard,
      year: t.enums(years()),
      month: t.enums(months()),
      cvc: t.Num
    });

    var options = {
      fields: {
        month: {
          nullOption: {value: '', text: 'Month'}
        },
        year: {
          nullOption: {value: '', text: 'Year'}
        }
      },
      templates: {
        struct: creditcard_layout,
        CreditCard: number_component
      }
    };
```

The 'number_component' should be applied to the field 'number', alas it's not. What am I doing wrong?

It also seems to me rather peculiar that one can't assign templates to fields by name. If the number field would be a simple t.Num then Num: number_component would also change the 'cvc' field.

**Comment by gcanti** [comment]
Oh sorry, docs show only the `templates` option (structs and lists). Actually you can pass a `template` option to a single field:

```js
var options = {
  fields: {
    number: {
      template: number_component // <--
    },
    month: {
      nullOption: {value: '', text: 'Month'}
    },
    year: {
      nullOption: {value: '', text: 'Year'}
    }
  },
  templates: {
    struct: creditcard_layout
  }
};
```

The file https://github.com/gcanti/tcomb-form/blob/master/lib/api.js contains a domain model
of the actual API (just in case)

**Comment by andrest** [comment]
Thanks a bunch! This works well
