### ISSUE TITLE
Can't give a list its own template

### ISSUE THREAD

**Issue by juice49** [gcanti/tcomb-form#69]
I am working with a form that has a list. I've found that the list correctly uses a template passed into `options.templates.list`, but I am unable to assign a template to a specific list inside of `options.fields.myListField.template`.

I have spent a little while poking my configuration to try and figure out if this is an error on my part, or a bug in tcomb-form. Other fields accept a template fine, so I have a feeling this may be a tcomb-form bug.

Here is an example configuration that shows both the working list template and the ignored list template (I'm not using them both together).

```
let options = {
	fields: {
		myListField: {
			// Individual field does not acknowledge this
			template: list
		}
	},
	templates: {
		// All list fields acknowledge this
		list
	}
};
```

I'm using tcomb-form 0.4.1 and React 0.12.2.

Thank you for this awesome library, it has been of much help to me (:

**Comment by gcanti** [comment]
Hi,
lists and structs have `templates` option (since they are containers). Textboxes, selects, etc have `template` option.

```js
let options = { // <- this is a struct, it has a `templates` option
    fields: {
        myListField: { // <- if this is a list...
            // ...should acknowledge this (`templates` option)
            templates: {
              list: list
            }
        }
    },
    templates: {
        // All list fields acknowledge this
        list
    }
};
```

> Thank you for this awesome library, it has been of much help to me (:

Thx, I'm glad to hear it

**Comment by juice49** [comment]
@gcanti Perhaps one of the best OSS maintainers I've seen!

That works perfectly, thanks for the quick response. I must have missed it in the docs.

**Comment by gcanti** [comment]
When in doubt, the file https://github.com/gcanti/tcomb-form/blob/master/lib/api.js contains the domain model of the actual API (just in case)

**Comment by juice49** [comment]
I'll be sure to reference that for future issues. Thanks again!
