### ISSUE TITLE
How do I perform a custom validation against an input?

### ISSUE THREAD

**Issue by astjohn** [gcanti/tcomb-form#70]
Thanks for the great library!

Can you please provide me with an example on how to validate an input of type email with a regular expression when the form is submitted?

I noticed that a field's options can contain an `error` attribute whose value is a function. However, it seems the function is called on a change event and that the context of the function isn't bound to anything in particular.

I'm not sure how to validate a specific field against a regular expression only when the form is submitted or ideally, when the field triggers a blur event.

**Comment by gcanti** [comment]
Hi, thanks.

> Can you please provide me with an example on how to validate an input of type email with a regular expression

```js
// use tcomb's type combinators (https://github.com/gcanti/tcomb)
var Email = t.subtype(t.Str, function (s) {
  return /^foo/.test(s);
});

var Type = t.struct({
  email: Email
});

<Form type={Type} />
```

> I noticed that a field's options can contain an error attribute whose value is a function

The `error` option can be a string, a JSX or a function

```js
var Email = t.subtype(t.Str, function (s) {
  return /^foo/.test(s);
});

var Type = t.struct({
  email: Email
});

var options = {
  fields: {
    email: {
      //error: 'my custom error message', // <-- fixed custom error message
      error: function (value) { // triggered when the field value changes
        return 'my custom error message: ' + value; // <-- custom error message based on current field value
      }
    }
  }
};

<Form type={Type} options={options} />
```

**Comment by astjohn** [comment]
Thanks for taking the time to explain this. It's extremely helpful to someone who is new to your libraries and it might make good material for the docs.

I'm not sure I would want the error function to fire onChange. I think in most of our use cases, we would want to fire it on form submit or perhaps on blur. However, if someone is tackling that other issue addressing other event binding, this probably won't be an issue.

**Comment by AlanVerbner** [comment]
@gcanti I'm struggling with something related to this.. 

If the user submits, the form hasErrors is true and the message is displayed. The thing is that while user fixes the email the error function is called each time the input is changed. Once the email is correct and error function doesn't return _'Invalid email'_ the input is still marked as error and shown with a red border which might be confusing (the email is valid, no error message but still in red). 

How can I trigger field validation again? Am I doing something wrong?

**Comment by gcanti** [comment]
I fixed the order of onChange and setState in all the components (thanks for pointing out).
Now you can call safely `getValue` in the `onChange` handler:

```js
var Email = t.subtype(t.Str, function (s) {
  return /^foo/.test(s);
});

var Type = t.struct({
  email: Email
});

var options = {
  fields: {
    email: {
      error: 'Invalid email' // <- fixed message
    }
  }
};

var App = React.createClass({
  getValue: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },
  onChange: function (value) {
    this.refs.form.getValue(); // <- validate on every change
  },
  render: function() {
    return (
      <div>
        <Form ref="form"
          type={Type}
          options={options}
          onChange={this.onChange} />
        <button className="btn btn-primary" onClick={this.getValue}>getValue</button>
      </div>
    );
  }
});

React.render(<App />, document.getElementById('app'));
```

**Comment by gcanti** [comment]
published v0.4.3 with the fix

**Comment by AlanVerbner** [comment]
Awesome. Works great.

Thanks @gcanti have a beer on me @ChangeTip.

**Comment by changetip** [comment]
Hi @gcanti, @AlanVerbner sent you a Bitcoin tip worth a beer (12,740 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/589614)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by gcanti** [comment]
Thanks @AlanVerbner, I appreciate ;-)
