### ISSUE TITLE
Allow removal of nullOption if a default value is set?

### ISSUE THREAD

**Issue by pillowsoft** [gcanti/tcomb-form#71]
First, thanks for creating such an awesome framework!

I am using labels on my fields right now. If I have an enum in the form and a initial data is set, I would prefer to not have the nullOption added to, or shown in the select dropdown, as I do not want a user to be able to choose it. Is there any way to accomplish this?

Thanks!

**Comment by gcanti** [comment]
Hi, thanks.

> I do not want a user to be able to choose it

At the moment it's not possible. I guess it makes sense if you have both a **required** enum and a initial data.

**Comment by pillowsoft** [comment]
Works great! Thanks!!
