### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Dignifiedquire** [gcanti/tcomb-form#72]
Hey,

I've been trying to get this great library running together with typescript. While I found definition files for `tcomb` itself, I'm having a hard time integrating them with `tcomb-form`. 

Any ideas/pointers how best to do that?

Thanks.

**Comment by gcanti** [comment]
Hi. 
These days I'm playing with TypeScript, I could try to write e definition file for tcomb-form and then discuss the result with you.

**Comment by Dignifiedquire** [comment]
I have worked on it a bit more, and got the basics working with this file: 

```typescript
// Type definitions for tcomb-form
// Definitions by: Friedel Ziegelmayer <https://github.com/dignifiedquire>

/// <reference path="../tcomb/tcomb.d.ts" />
/// <reference path="../react/react.d.ts" />

declare module tcomb {

    /* API Elements */

    interface I18n {}

    interface NumberTransformer {}

    interface Transformer {
        Num: NumberTransformer;
    }

    interface Irreducibles {
        Bool: Checkbox;
    }

    interface Config {
        i18n: I18n;
        transformers: Transformer;
        irreducibles: Irreducibles;
    }

    /* Components */

    interface Form extends React.ReactElement<any> {
        getValue(raw?: boolean): void;
        getValue(raw?: boolean): any;
    }

    interface Textbox extends React.ReactElement<any> {}
    interface Select extends React.ReactElement<any> {}
    interface Checkbox extends React.ReactElement<any> {}
    interface Radio extends React.ReactElement<any> {}
    interface Struct extends React.ReactElement<any> {}
    interface List extends React.ReactElement<any> {}


    interface FormStatic {
        config: Config;
        Form: Form;
        Textbox: Textbox;
        Select: Select;
        Checkbox: Checkbox;
        Radio: Radio;
        Struct: Struct;
        List: List;
    }

    export var form: FormStatic;
}


declare module 'tcomb-form' {
    import Export = tcomb;
    export = Export;
}
```

I'd be happy to collaborate with you to get this cleaned up and published onto definitelytyped.org

**Comment by gcanti** [comment]
> I'd be happy to collaborate with you to get this cleaned up and published onto definitelytyped.org

Great.

This is my attempt (feel free to modify | merge | discard what you want - I'm still a newbie in TypeScript)

https://github.com/gcanti/tcomb-form/blob/master/definitions/tcomb-form.d.ts

**Comment by Dignifiedquire** [comment]
@gcanti great, I started using it, for any more issues see #73.

**Comment by caesay** [comment]
@gcanti I see the definition file got deleted in commit 00a46d7, any reason this was abandoned?
