### ISSUE TITLE
Reason for not using JSON schema

### ISSUE THREAD

**Issue by vespakoen** [gcanti/tcomb-form#74]
Hi there!

I am building a CMS with react, and was looking for a form library when stubling upon yours.
It looks very nice!

I wonder though, what do you feel is JSON schema lacking, for you to choose to roll your own?

Since you like high-level-ish things, you might be interested in checking out my "dynamic store" project (WIP but very usable already!)

It "migrates" databases based on a schema defined in JSON (& validated by a JSON-schema), keeps track of changes between versions, and automatically keeps your data compatible between different versions of the schema.

www.github.com/trappsnl/dstore

**Comment by gcanti** [comment]
Hi!

> I wonder though, what do you feel is JSON schema lacking, for you to choose to roll your own?

JSON Schema is great, but I needed a way to define:

- types with compact syntax (JSON Schema is quite verbose)
- integration with tcomb and tcomb-validation libraries
- custom types (tcomb's `irreducible`)
- **subtypes (tcomb's `subtype`)**

There's also a library (https://github.com/gcanti/tcomb-json-schema) which converts a JSON Schema to tcomb types.

**Comment by vespakoen** [comment]
I see... should have checked the `tcomb` project page before asking the question!

Anyways, it looks really cool! thanks for the answer
