### ISSUE TITLE
Input className customization

### ISSUE THREAD

**Issue by ericdfields** [gcanti/tcomb-form#76]
I'm doing a few exercises comparing tcomb-form to newforms to figure out which is better suited for my project. Right now I'm stuck trying to add a simple html class to a t.Str. I'd love for something like the following to "just work":

````javascript
var options = {
  fields: {
    birth_date: {
      className: 'datepicker'
    }
  }
}
````

I can see already in the source that I built (bootstrap theme I suppose) that `form-control` is the given class name and there's no adding of others. Is the only way to customize a form this simply to create a new template? I'm not opposed to doing so, but it seems I run the risk of creating lots of mini templates with a lot of duplicate boilerplate code for simple text inputs. 

I'd love to simply be able to extend Textbox somehow. Is there an easier way? Has this been considered?

Thank you.

**Comment by gcanti** [comment]
> Is the only way to customize a form this simply to create a new template?

Usually for simple customizations I work at the css level. Is it an option for you?

**Comment by ericdfields** [comment]
To an extent, sure. That example I gave will auto-trigger a date picker pop-up on an input with the class `datepicker`, which is a pretty common practice.

**Comment by gcanti** [comment]
Ok, my plan:

1. add a `className` option to:
  - `Textbox`
  - `Select`
  - `Checkbox`
  - `Radio`
  - `List`
  - `Struct`

2. handle this new option in Bootstrap's skin like this:
  - `Textbox`: add the className to the `<input type="text"/>` / `<textarea/>` tag
  - `Select`: add the className to the `<select/>` tag
  - `Checkbox`: add the className to the `<input type="checkbox"/>` tag
  - `Radio`: add the className to **all** the `<input type="radio"/>` tags
  - `List`: add the className to the `<fieldset/>` tag
  - `Struct`: add the className to the `<fieldset/>` tag

What do you think?

**Comment by ericdfields** [comment]
I’d say that’s a fine start. Can it be more generic to allow for arbitrary attribute passing? I’m thinking data-*/aria-* attributes…

**Comment by gcanti** [comment]
reopening for v0.5 milestone

**Comment by aimeeroxanne** [comment]
Is there documentation on the 'attrs' option anywhere?
