### ISSUE TITLE
Using custom controls

### ISSUE THREAD

**Issue by PetrSnobelt** [gcanti/tcomb-form#82]
What is recommended way how to use third-party controls like:
http://brianreavis.github.io/selectize.js/
http://www.jacklmoore.com/autosize/
datepicker etc..

Can you add sample to playground?

BTW: Thanks for nice library

**Comment by gcanti** [comment]
For autosize (based on its decumentation) it should be easy:

```js
var React = require('react');
var t = require('tcomb-form');
var autosize = require('autosize');

var Form = t.form.Form;

var Type = t.struct({
  text: t.Str
});

var options = {
  fields: {
    text: {
      id: 'text',
      type: 'textarea'
    }
  }
};

var App = React.createClass({

  componentDidMount: function () { // <-- add autosize
    autosize(document.getElementById('text'));
  },

  componentWillUnmount: function () { // <-- remove autosize
    var evt = document.createEvent('Event');
    evt.initEvent('autosize.destroy', true, false);
    document.getElementById('text').dispatchEvent(evt);
  },

  getValue: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render: function() {
    return (
      <div>
        <Form ref="form"
          type={Type}
          options= {options} />
        <button className="btn btn-primary" onClick={this.getValue}>getValue</button>
      </div>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Comment by gcanti** [comment]
For more complex widgets, it depends: you could write a custom template or a custom component (factory) see http://gcanti.github.io/tcomb-form/guide/index.html#templates and folowing sections.

Note: In React, even more so than other data-bound frameworks, 
you should try not to manipulate the DOM directly if at all possible.

**Comment by PetrSnobelt** [comment]
thank you for examples. I expected that if I have 2 textboxes and only one should have autogrow I need custom template? Maybe you should add support for class property into available options, which can help with it.

Will be great if you add example of templates into playground.

I know about react aproach, but there are still lack of some advanced react controls...

**Comment by gcanti** [comment]
>  I expected that if I have 2 textboxes and only one should have autogrow I need **custom template**?

No need for that setting the id of the proper textarea:

```js
var Type = t.struct({  // <-- 2 textareas
  textarea1: t.Str,
  textarea2: t.Str
});

var options = {
  fields: {
    textarea1: {
      id: 'mytextarea1',
      type: 'textarea'
    },
    textarea2: {
      type: 'textarea'
    }
  }
};

...


  componentDidMount: function () { // <-- add autosize only to mytextarea1
    autosize(document.getElementById('mytextarea1'));
  },

  componentWillUnmount: function () { // <-- remove autosize
    var evt = document.createEvent('Event');
    evt.initEvent('autosize.destroy', true, false);
    document.getElementById('mytextarea1').dispatchEvent(evt);
  },


```

BTW I've just added today the support for the `className` option (v0.4.4)

> I know about react aproach, but there are still lack of some advanced react controls...

You're right. Anyway React and jQuery (for example) *can* definitely play well together, you just have to be a little careful.

**Comment by blaflamme** [comment]
@gcanti any clues or snippets about how to use a component like this one with tcomb-form ? http://jedwatson.github.io/react-select/
