### ISSUE TITLE
Conditional required fields

### ISSUE THREAD

**Issue by nanodocumet** [gcanti/tcomb-form#83]
Hi there,

Imagine a form such as:

1) Name (required) - string
2) Email (optional) - string
3) Favorite sport (required) - select with option for other
4) Other Favorite sport (optional) - to be required when Favorite sport is **Other**, otherwise optional.
5) Favorite color (required) - select with option for other
6) Other Favorite color (optional) - to be required when Favorite color is **Other**, otherwise optional.

How can the following be achieved?
1) Show the conditional required fields accordingly. Other Favorite sport and Other Favorite color when the **Other** option is picked.
2) Form should be valid when there are no values for the **Other** fields and the values of the favorite things are not "Other". This probably leads to mark the **Other** fields as `t.maybe(t.Str)`
3) However, with "maybe" the labels show with "(optional)" at the end, I know I can set the label for those fields manually, but it will be nice if they get updated accordingly.
4) Notice that there could be more than just 1 conditional, thus, logic could be complicated if we use a the predicate and treat everything as a subtype. I took a look at the example from the docs "Advanced form validation Struct subtypes" but it still fails on items 1 and 3.

Thus, is it possible to change a field from `t.maybe(t.Str)` to `t.Str` at runtime? That way, all the goodness of required fields will come for free (labels, validations, errors)

Just doing the hide/show of the field based on the option picked for the select will make the **Other** fields pass the form validation if they are empty when using `t.maybe`.

Thanks!

**Comment by gcanti** [comment]
> Thus, is it possible to change a field from t.maybe(t.Str) to t.Str at runtime? That way, all the goodness of required fields will come for free (labels, validations, errors)

Yes it is. Though, without dropping 1) requirement, I'm afraid you would end up with a lot of code to handle all cases.
Something similar to your https://github.com/gcanti/tcomb-form/issues/78: build `Type` and `options` at runtime based on the form value

**Comment by gcanti** [comment]
> Though, without dropping 1) requirement, I'm afraid you would end up with a lot of code

Hey,
thinking twice and using a `getType(value)` helper, the code is not **so** verbose:

```js
var React = require('react');
var t = require('tcomb-form');

var Form = t.form.Form;

var Sport = t.enums({
  football: 'Football',
  baseball: 'Baseball',
  other: 'Other'
});

var Color = t.enums({
  green: 'Green',
  blue: 'Blue',
  other: 'Other'
});

// returns the proper struct based on the value in the form
function getType(value) {
  var props = { // fixed fields
    name: t.Str,
    email: t.maybe(t.Str),
    favoriteSport: Sport
  };
  if (value.favoriteSport === 'other') {
    props.otherFavoriteSport = t.Str; // required and visible
  }
  props.favoriteColor = Color; // another fixed field
  if (value.favoriteColor === 'other') {
    props.otherFavoriteColor = t.Str; // required and visible
  }
  return t.struct(props);
}

var App = React.createClass({

  getInitialState: function () {
    return {
      type: getType({}),
      value: {}
    };
  },

  onChange: function (value) {
    this.setState({
      type: getType(value),
      value: value
    });
  },

  save: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render: function() {
    return (
      <div>
        <Form ref="form"
          type={this.state.type}
          value={this.state.value}
          onChange={this.onChange} />
        <button className="btn btn-primary" onClick={this.save}>Save</button>
      </div>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

Are all your requirements satisfied by that?

**Comment by nanodocumet** [comment]
Thanks Giulio for your prompt responses! I will check your second response and let you know how it goes.

Thanks!

**Comment by nanodocumet** [comment]
Works great and exactly what I was looking for. Certainly having it built-in might be nicer, maybe by adding a `required` and a `visible` combination that can take boolean/function values, but that might change how the form does it right now which considers `maybe` as the optional field.

Thanks!

**Comment by pscanf** [comment]
I have just finished developing something that does more or less that. It would allow you to define a schema such as:

```js
{
    type: "object",
    shape: {
        name: {
            type: "string"
        },
        email: {
            type: "string",
            optional: true
        },
        favoriteSport: {
            type: "string",
            allowedValues: [
                "Football",
                "Baseball",
                "Tennis",
                "Other"
            ]
        },
        otherFavoriteSport: {
            if: {
                favoriteSport: "Other"
            },
            type: "string"
        },
        favoriteColor: {
            type: "string",
            allowedValues: [
                "Green",
                "Red",
                "Blue",
                "Other"
            ]
        },
        otherFavoriteColor: {
            if: {
                favoriteColor: "Other"
            },
            type: "string"
        }
}
```

From that schema, it generates the correct tcomb-form. It's a thin wrapper (~70loc) around tcomb-form, so it gives you most of tcomb's features. Right now it's internal to a work project, but I plan on publishing it fairly soon. Feel free to ping me if you're interested. :-)

**Comment by arnoldbird** [comment]
@pscanf 
Just wondering if you published anything similar to what you've described above.  Did your wrapper work pretty well in practice?  I'd certainly like to give it a try if it's something you can publish.  Thanks

**Comment by pscanf** [comment]
Yes, I did publish [mondora/tcomb-conditional-forms](https://github.com/mondora-labs/tcomb-conditional-forms) ([npm link](https://www.npmjs.com/package/tcomb-conditional-forms)) and a side-kick library [mondora-labs/tcomb-input-collection](https://github.com/mondora-labs/tcomb-input-collection). Unfortunately the libraries are not documented aside from an example, and they use a very old version of tcomb-form. But maybe it can be useful to poke around the source.

Cheers
