### ISSUE TITLE
Ability to subclass/extend t.form.textbox with es6 classes

### ISSUE THREAD

**Issue by nelix** [gcanti/tcomb-form#85]
This would make tempting and writing custom components way easier

**Comment by gcanti** [comment]
(issue noted, I'm thinking about it... nice suggestion, thanks)

**Comment by gcanti** [comment]
@nelix Something like this (experimental branch v0.5)?

The base `Component`:

https://github.com/gcanti/tcomb-form/blob/v0.5/lib/components/Component.js

The `Textbox` component (extends `Component`)

https://github.com/gcanti/tcomb-form/blob/v0.5/lib/components/Textbox.js

**Comment by nelix** [comment]
Yeah that would look really nice from the outside to those using es6 classes I think.
Some detailed documentation for the lifecycle of a tcomb component would help.

**Comment by gcanti** [comment]
v0.5-alpha on master

missing:
- tests (complete code coverage)
- docs
- guide
- demos

**Comment by gcanti** [comment]
v0.5-alpha on master

missing:
- tests (complete code coverage)
- docs
- guide
- demos

@Chrisui

**Comment by gcanti** [comment]
Changelog till now

- Support bootstrap static controls
- Support min/max for number type
- Support attributes and input className customization
- Pass events to inputs
- Set class on form-group div indicating its depth within form
- added Form.getComponent(path) API to access form components

Now you can implement a basic custom component in a few lines:

```js
class MyComponent extends t.form.Component {

  // the only required implementation
  getTemplate() {
    return (locals) => {
      return (
        <div onClick={locals.onChange.bind(this, 'world')}>
          Hello {locals.value}
        </div>
      );
    };
  }

}
```

**Comment by Chrisui** [comment]
Looks good.

Do you still pass this through with the form options? Ie. does it replace 'templates' option? (sorry haven't had chance to trawl the code too much! :)

**Comment by gcanti** [comment]
The `template` option is still in place. This is useful if you want to write a custom component (`factory` option)
