### ISSUE TITLE
Subform custom component?

### ISSUE THREAD

**Issue by mattem** [gcanti/tcomb-form#86]
I was wondering if it is possible, with a custom component or other means, to present a drop down select to the user (like t.enum does) but containing a list of 'pluggable' subforms (t.struct), which when one is selected, would display the form for that item. Selecting a different item would then remove the old form, and show the selected one. 

For example, you could have a 'Transport Type' drop down containing items such as 'Car', 'Bike', 'Walking', and when one is selected, the form for Car is displayed, or Bike etc.

**Comment by gcanti** [comment]
Hi, 
same as https://github.com/gcanti/tcomb-form/issues/83, 
no need for a custom component:

```js
var React = require('react');
var t = require('tcomb-form');

var Form = t.form.Form;

var TransportType = t.enums.of('Car Bike');

var Car = t.struct({
  carField1: t.Str,
  carField2: t.Str
});

var Bike = t.struct({
  bikeField1: t.Str,
  bikeField2: t.Str
});

// returns the proper struct based on form's value
function getType(value) {
  var props = {
    type: TransportType
  };
  if (value.type === 'Car') {
    props.car = Car; // or t.mixin(props, Car.meta.props)
  }
  else if (value.type === 'Bike') {
    props.bike = Bike; // or t.mixin(props, Bike.meta.props)
  }
  return t.struct(props);
}

var App = React.createClass({

  getInitialState: function () {
    return {
      type: getType({}),
      value: {}
    };
  },

  onChange: function (value) {
    this.setState({
      type: getType(value),
      value: value
    });
  },

  save: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render: function() {
    return (
      <div>
        <Form ref="form"
          type={this.state.type}
          value={this.state.value}
          onChange={this.onChange} />
        <button className="btn btn-primary" onClick={this.save}>Save</button>
      </div>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Comment by mattem** [comment]
This is perfect. Thank you!

**Comment by chollier** [comment]
I'm glad to see you using setState, it was super-weird for me to see `this.state.something = something` in the docs : http://gcanti.github.io/tcomb-form/guide/index.html#controlled-forms — I think that should be corrected as we're not supposed to mutate the state directly

**Comment by gcanti** [comment]
@chollier Not sure why it's like that. I agree with you. it's weird. I'll fix it
