### ISSUE TITLE
Set value of field based on selection

### ISSUE THREAD

**Issue by nanodocumet** [gcanti/tcomb-form#87]
Hi,

I will like to be able to set the value of a field based on the option picked from a select. Simplified example:

- City: Select. Values: Los Angeles, New York, Milan
- Country: String

So, when Los Angeles or New York is picked, country becomes "USA", but when Milan is picked, country becomes "Italy". For both cases, also mark Country as disable/readonly.

Is there any easy way to add this behavior to a form?

Thanks!

Nano.

**Comment by gcanti** [comment]
#78, #83 

build `type` and/or `value` and/or `options` at runtime:

```js
onChange: function (value) {
  this.setState({
    type: getType(value),
    options: getOptions(value),
    value: getValue(value),
  });
}

...

<Form ref="form"
  type={this.state.type}
  options={this.state.options}
  value={this.state.value}
  onChange={this.onChange} 
/>
```

**Comment by nanodocumet** [comment]
Here is the issue I am facing.

From the logic below, when `Football` is picked, `favoriteColor` should be `Green`, this is all good and works.

However, when `Baseball` is picked (trying to reset `favoriteColor`), the value for `favoriteColor` stays with `Green` (should be back to `null`), but the `internal` value seems to be correct, not the displayed value. If `Save` is pressed, `favoriteColor` gets highlighted as it contains error, which is correct. Is this a bug? How can the other select be __reset__? Resetting works fine for textboxes, just not for selects.

Also. For the `onChange` function at the `Form` level, it will be nice to know the fieldName and fieldValue that triggered the change. So `onChange: function (value)` becomes `onChange: function (value, fieldName, fieldValue)` similarly to how Struct's onChange signature is.

```javascript
var React = require('react');
var t = require('tcomb-form');

var Form = t.form.Form;

var Sport = t.enums({
  football: 'Football',
  baseball: 'Baseball',
  other: 'Other'
});

var Color = t.enums({
  green: 'Green',
  blue: 'Blue',
  other: 'Other'
});

// returns the proper struct based on the value in the form
function getType(value) {
  var props = { // fixed fields
    name: t.Str,
    email: t.maybe(t.Str),
    favoriteSport: Sport
  };
  if (value.favoriteSport === 'other') {
    props.otherFavoriteSport = t.Str; // required and visible
  }
  props.favoriteColor = Color; // another fixed field
  if (value.favoriteColor === 'other') {
    props.otherFavoriteColor = t.Str; // required and visible
  }
  return t.struct(props);
}

// returns the proper struct based on the value in the form
function getValue(value) {
  if (value.favoriteSport && value.favoriteSport === 'football') {
    value.favoriteColor = 'green';
  }
  if (value.favoriteSport && value.favoriteSport === 'baseball') {
    value.favoriteColor = null;
    // delete does not work either
    //delete value.favoriteColor
  }

  return value;
}

var App = React.createClass({

  getInitialState: function () {
    return {
      type: getType({}),
      value: {}
    };
  },

  onChange: function (value) {
    this.setState({
      type: getType(value),
      value: getValue(value)
    });
  },

  save: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render: function() {
    return (
      <div>
        <Form ref="form"
          type={this.state.type}
          value={this.state.value}
          onChange={this.onChange} />
        <button className="btn btn-primary" onClick={this.save}>Save</button>
      </div>
    );
  }

});

React.render(<App />, document.getElementById('app'));
```

**Comment by gcanti** [comment]
> How can the other select be reset? Resetting works fine for textboxes, just not for selects.

In order to reset a select you must pass the `nullOption`'s value (`null` is an "undefined behaviour"), so in the default case case `""`:

```js
value.favoriteColor = "";
```

**Comment by nanodocumet** [comment]
That works, but wondering why having `delete value.favoriteColor` does not work. Setting the value to `""` means that empty value, or no key for that field represent the same thing. It will be nice to have the capability to handle it in a single way.

But from the example above, having the value of `favoriteSport` set to `Football` will not allow to have the value for `favoriteColor` being changed, since `favoriteSport` is always `Football`, `favoriteColor` will always be `Green`. Knowing what field changed might help with that.

Thanks for all your help!

**Comment by gcanti** [comment]
> It will be nice to have the capability to handle it in a single way

I agree, this line should fix it

https://github.com/gcanti/tcomb-form/blob/master/lib/components/Select.js#L81

**Comment by gcanti** [comment]
> But from the example above, having the value of favoriteSport set to Football will not allow to have the value for favoriteColor being changed, since favoriteSport is always Football, favoriteColor will always be Green. Knowing what field changed might help with that.

I'll think about a nice API. As a workaround, what about diffing `newValue` and `oldValue`?

```js
function getValue(newValue, oldValue) {
  if (newValue.favoriteSport !== oldValue.favoriteSport && newValue.favoriteSport === 'football') {
    newValue.favoriteColor = 'green';
  }
  if (newValue.favoriteSport === 'baseball') {
    delete newValue.favoriteColor;
  }

  return newValue;
}

...

onChange: function (value) {
  this.setState({
    type: getType(value),
    value: getValue(value, this.state.value)
  });
}

```

**Comment by nanodocumet** [comment]
Nice! I like that commit!

I can leave with that workaround for the moment until a nice API is implemented. Looking forward to see the update in npm.

Thanks!
