### ISSUE TITLE
Numeric field does not render decimal mark on input

### ISSUE THREAD

**Issue by vasa-chi** [gcanti/tcomb-form#89]
If you try to enter `123.45` into Age field in [this example](http://gcanti.github.io/tcomb-form/guide/index.html#numeric-field), the field does not render the decimal mark on input, so I have to input `12345`, then place the dot between 3 and 4.

**Comment by gcanti** [comment]
Should be fixed now, thx!

**Comment by vasa-chi** [comment]
Thank you :)
