### ISSUE TITLE
Support transformers for other components

### ISSUE THREAD

**Issue by pscanf** [gcanti/tcomb-form#90]
Reading through the source it seems like transformers are only supported for `Textbox`-s. Would it be possible to extend support to other components like `Struct`-s?

I was wondering if simply adding in `lib/components/Struct.js` something like
```js
    var transformer = opts.transformer || config.transformers[t.getTypeName(ctx.report.innerType)];
    if (transformer) {
      value = transformer.format(value);
    }
    return {
      // [...]
      onChange: function (value) {
        if (transformer) {
          value = transformer.parse(value);
        }
        this.onChange(value);
      }.bind(this),
      // [...]
    };
```
might do the trick, or if it'd just break everything :-) . I suspect there could be troubles with transformers for fields inside the `struct`, by I don't know the codebase by heart, so I ask. :-)

Thanks

**Comment by gcanti** [comment]
Hi, interesting. 
Technically I think it wouldn't be a problem. What's your use case for this?

**Comment by gcanti** [comment]
Ciao Paolo, fammi sapere se la modifica che ho fatto ti basta.

**Comment by pscanf** [comment]
Hi Giulio, sorry for not replying earlier, and thanks for the quick support. :-)

My use case is the following:

I have an object with a property, let's call it `prop_0`, which the user needs to modify. However, I don't want the user to edit `prop_0` directly, but rather a set of properties, let's say `prop_1`, `prop_2` and `prop_3`, which are then used to determine the value of `prop_0`.

There are of course multiple ways of accomplishing this. Right now, for instance, I'm doing it in a component which wraps the tcomb-form. However, I thought a transformer could be a cleaner, terser and more declarative solution.

I've quickly browsed through the commit but couldn't really tell if the new implementation can fit my use case (I just came back from a wedding and I'm a bit tipsy :-) ). Anyway, tomorrow I'll give a try to `v0.4.7/8` and I'll let you know.

Thanks again!
