### ISSUE TITLE
Path is empty for errors from getValue(raw = true)

### ISSUE THREAD

**Issue by Firfi** [gcanti/tcomb-form#94]
I create this issue not in tcomb-validation as don't have time to check this library separately. Probably it is validation library issue but might be form as well.

My goal is getting error messages (or at least information which field have an error) from getValue(true).

I have schema like 

    var Positive = t.subtype(t.Num, function(n) {
      return n > 0;
    });

    var BillingSubscriptionFormModel = t.struct({
      subscriptionType: t.enums({
        monthly: 'Monthly',
        yearly: 'Yearly'
      }),
      attendants: Positive
    });

Later in code, I call created form by ref: `this.refs.form.getValue(true);`. 

Resulting ValidationResult have ValidationErrors with empty paths.

**Comment by gcanti** [comment]
This is disappointing, I'll fix that asap, thanks.
