### ISSUE TITLE
[Feature request] give possibility to place <button type="submit"> inside generated form

### ISSUE THREAD

**Issue by Firfi** [gcanti/tcomb-form#95]
I find it strange there's no such request. Am I overlooked it? 

Case is like this: I create form like that:

    <Form .../>
    <button type="submit"/>

Problem is, when focus is inside any input, and I click 'enter', button submit doesn't being clicked (and it shouldn't as it isn't inside <form>.

I'd like to have possibility to have this button inside, not using custom templates / custom components.

**Comment by gcanti** [comment]
The output of the `Form` component is a `fieldset` tag containing the fields. You can add a form tag wrapping the output:

```js
<form action="..." method="..." or onClick={...}>
  <Form ... />
  <button type="submit"/>
</form>
```

**Comment by Firfi** [comment]
Thanks!
