### ISSUE TITLE
Validation and re-validation when leaving a field

### ISSUE THREAD

**Issue by ustun** [gcanti/tcomb-form#96]
Is there a way to validate and revalidate a field upon leaving it, blur? I looked into the docs, but wasn't able to find this.

To implement this, each field would probably need a "dirty" flag and only show the error if that dirty flag is set or the form has been attempted to be submitted at least once.

**Comment by gcanti** [comment]
> Is there a way to validate and revalidate a field upon leaving it, blur?

At the moment no, I think you'll be able to do that when https://github.com/gcanti/tcomb-form/issues/53 lends in v0.5

**Comment by gcanti** [comment]
Hi @ustun, I wrote an example for v0.5 (currently on master branch). Is it helpful?

https://github.com/gcanti/tcomb-form/issues/101
